namespace PIM.View
{
    partial class frmCadastro_funcionario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCadastro_funcionario));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.lblSexo = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxNome = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblDataNascimento = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.TextBoxCNH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCnh = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btn_Sair_ENTREGAS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Salvar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblEndereco = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblEmail = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEndereco = new System.Windows.Forms.RichTextBox();
            this.TextBoxCelular = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCelular = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxCPF = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCpf = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxRG = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblRG = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxTelefone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblTelefone = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxDataNascimento = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblNome = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxSexo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblSexo
            // 
            this.lblSexo.AutoSize = true;
            this.lblSexo.Location = new System.Drawing.Point(584, 33);
            this.lblSexo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblSexo.Name = "lblSexo";
            this.lblSexo.Size = new System.Drawing.Size(39, 17);
            this.lblSexo.TabIndex = 0;
            this.lblSexo.Text = "Sexo";
            // 
            // TextBoxNome
            // 
            this.TextBoxNome.AcceptsReturn = false;
            this.TextBoxNome.AcceptsTab = false;
            this.TextBoxNome.AnimationSpeed = 200;
            this.TextBoxNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxNome.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxNome.BackgroundImage")));
            this.TextBoxNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxNome.BorderRadius = 1;
            this.TextBoxNome.BorderThickness = 1;
            this.TextBoxNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxNome.DefaultText = "";
            this.TextBoxNome.FillColor = System.Drawing.Color.White;
            this.TextBoxNome.HideSelection = true;
            this.TextBoxNome.IconLeft = null;
            this.TextBoxNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.IconPadding = 10;
            this.TextBoxNome.IconRight = null;
            this.TextBoxNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.Lines = new string[0];
            this.TextBoxNome.Location = new System.Drawing.Point(128, 21);
            this.TextBoxNome.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxNome.MaxLength = 32767;
            this.TextBoxNome.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxNome.Modified = false;
            this.TextBoxNome.Multiline = false;
            this.TextBoxNome.Name = "TextBoxNome";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnIdleState = stateProperties4;
            this.TextBoxNome.PasswordChar = '\0';
            this.TextBoxNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.PlaceholderText = "";
            this.TextBoxNome.ReadOnly = false;
            this.TextBoxNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxNome.SelectedText = "";
            this.TextBoxNome.SelectionLength = 0;
            this.TextBoxNome.SelectionStart = 0;
            this.TextBoxNome.ShortcutsEnabled = true;
            this.TextBoxNome.Size = new System.Drawing.Size(311, 43);
            this.TextBoxNome.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxNome.TabIndex = 4;
            this.TextBoxNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxNome.TextMarginBottom = 0;
            this.TextBoxNome.TextMarginLeft = 5;
            this.TextBoxNome.TextMarginTop = 0;
            this.TextBoxNome.TextPlaceholder = "";
            this.TextBoxNome.UseSystemPasswordChar = false;
            this.TextBoxNome.WordWrap = true;
            this.TextBoxNome.TextChanged += new System.EventHandler(this.TextBoxNome_TextChanged);
            // 
            // lblDataNascimento
            // 
            this.lblDataNascimento.AutoSize = true;
            this.lblDataNascimento.Location = new System.Drawing.Point(39, 101);
            this.lblDataNascimento.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblDataNascimento.Name = "lblDataNascimento";
            this.lblDataNascimento.Size = new System.Drawing.Size(78, 17);
            this.lblDataNascimento.TabIndex = 3;
            this.lblDataNascimento.Text = "Data Nasc.";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.Black;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(16, 31);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(279, 31);
            this.bunifuLabel1.TabIndex = 6;
            this.bunifuLabel1.Text = "Cadastro de Funcionario";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCNH);
            this.bunifuShadowPanel1.Controls.Add(this.lblCnh);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Sair_ENTREGAS);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Salvar);
            this.bunifuShadowPanel1.Controls.Add(this.lblEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEmail);
            this.bunifuShadowPanel1.Controls.Add(this.lblEmail);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCelular);
            this.bunifuShadowPanel1.Controls.Add(this.lblCelular);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCPF);
            this.bunifuShadowPanel1.Controls.Add(this.lblCpf);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxRG);
            this.bunifuShadowPanel1.Controls.Add(this.lblRG);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.lblTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxDataNascimento);
            this.bunifuShadowPanel1.Controls.Add(this.lblNome);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxSexo);
            this.bunifuShadowPanel1.Controls.Add(this.lblSexo);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxNome);
            this.bunifuShadowPanel1.Controls.Add(this.lblDataNascimento);
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(16, 71);
            this.bunifuShadowPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(1049, 686);
            this.bunifuShadowPanel1.TabIndex = 8;
            // 
            // TextBoxCNH
            // 
            this.TextBoxCNH.AcceptsReturn = false;
            this.TextBoxCNH.AcceptsTab = false;
            this.TextBoxCNH.AnimationSpeed = 200;
            this.TextBoxCNH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCNH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCNH.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCNH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCNH.BackgroundImage")));
            this.TextBoxCNH.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCNH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCNH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCNH.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCNH.BorderRadius = 1;
            this.TextBoxCNH.BorderThickness = 1;
            this.TextBoxCNH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCNH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCNH.DefaultText = "";
            this.TextBoxCNH.FillColor = System.Drawing.Color.White;
            this.TextBoxCNH.HideSelection = true;
            this.TextBoxCNH.IconLeft = null;
            this.TextBoxCNH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.IconPadding = 10;
            this.TextBoxCNH.IconRight = null;
            this.TextBoxCNH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.Lines = new string[0];
            this.TextBoxCNH.Location = new System.Drawing.Point(633, 161);
            this.TextBoxCNH.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxCNH.MaxLength = 32767;
            this.TextBoxCNH.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCNH.Modified = false;
            this.TextBoxCNH.Multiline = false;
            this.TextBoxCNH.Name = "TextBoxCNH";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnIdleState = stateProperties8;
            this.TextBoxCNH.PasswordChar = '\0';
            this.TextBoxCNH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.PlaceholderText = "";
            this.TextBoxCNH.ReadOnly = false;
            this.TextBoxCNH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCNH.SelectedText = "";
            this.TextBoxCNH.SelectionLength = 0;
            this.TextBoxCNH.SelectionStart = 0;
            this.TextBoxCNH.ShortcutsEnabled = true;
            this.TextBoxCNH.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCNH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCNH.TabIndex = 33;
            this.TextBoxCNH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCNH.TextMarginBottom = 0;
            this.TextBoxCNH.TextMarginLeft = 5;
            this.TextBoxCNH.TextMarginTop = 0;
            this.TextBoxCNH.TextPlaceholder = "";
            this.TextBoxCNH.UseSystemPasswordChar = false;
            this.TextBoxCNH.WordWrap = true;
            // 
            // lblCnh
            // 
            this.lblCnh.AutoSize = true;
            this.lblCnh.Location = new System.Drawing.Point(584, 174);
            this.lblCnh.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCnh.Name = "lblCnh";
            this.lblCnh.Size = new System.Drawing.Size(37, 17);
            this.lblCnh.TabIndex = 32;
            this.lblCnh.Text = "CNH";
            // 
            // btn_Sair_ENTREGAS
            // 
            this.btn_Sair_ENTREGAS.AllowToggling = false;
            this.btn_Sair_ENTREGAS.AnimationSpeed = 200;
            this.btn_Sair_ENTREGAS.AutoGenerateColors = false;
            this.btn_Sair_ENTREGAS.BackColor = System.Drawing.Color.Transparent;
            this.btn_Sair_ENTREGAS.BackColor1 = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Sair_ENTREGAS.BackgroundImage")));
            this.btn_Sair_ENTREGAS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sair_ENTREGAS.ButtonText = "Sair";
            this.btn_Sair_ENTREGAS.ButtonTextMarginLeft = 0;
            this.btn_Sair_ENTREGAS.ColorContrastOnClick = 45;
            this.btn_Sair_ENTREGAS.ColorContrastOnHover = 45;
            this.btn_Sair_ENTREGAS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_Sair_ENTREGAS.CustomizableEdges = borderEdges1;
            this.btn_Sair_ENTREGAS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Sair_ENTREGAS.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_Sair_ENTREGAS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Sair_ENTREGAS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Sair_ENTREGAS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Sair_ENTREGAS.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btn_Sair_ENTREGAS.ForeColor = System.Drawing.Color.White;
            this.btn_Sair_ENTREGAS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Sair_ENTREGAS.IconMarginLeft = 11;
            this.btn_Sair_ENTREGAS.IconPadding = 10;
            this.btn_Sair_ENTREGAS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Sair_ENTREGAS.IdleBorderColor = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.IdleBorderRadius = 3;
            this.btn_Sair_ENTREGAS.IdleBorderThickness = 1;
            this.btn_Sair_ENTREGAS.IdleFillColor = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.IdleIconLeftImage = null;
            this.btn_Sair_ENTREGAS.IdleIconRightImage = null;
            this.btn_Sair_ENTREGAS.IndicateFocus = false;
            this.btn_Sair_ENTREGAS.Location = new System.Drawing.Point(931, 612);
            this.btn_Sair_ENTREGAS.Margin = new System.Windows.Forms.Padding(4);
            this.btn_Sair_ENTREGAS.Name = "btn_Sair_ENTREGAS";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties9.BorderRadius = 3;
            stateProperties9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties9.BorderThickness = 1;
            stateProperties9.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties9.ForeColor = System.Drawing.Color.White;
            stateProperties9.IconLeftImage = null;
            stateProperties9.IconRightImage = null;
            this.btn_Sair_ENTREGAS.onHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties10.BorderRadius = 3;
            stateProperties10.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties10.BorderThickness = 1;
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties10.ForeColor = System.Drawing.Color.White;
            stateProperties10.IconLeftImage = null;
            stateProperties10.IconRightImage = null;
            this.btn_Sair_ENTREGAS.OnPressedState = stateProperties10;
            this.btn_Sair_ENTREGAS.Size = new System.Drawing.Size(79, 43);
            this.btn_Sair_ENTREGAS.TabIndex = 30;
            this.btn_Sair_ENTREGAS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Sair_ENTREGAS.TextMarginLeft = 0;
            this.btn_Sair_ENTREGAS.UseDefaultRadiusAndThickness = true;
            // 
            // btn_Salvar
            // 
            this.btn_Salvar.AllowToggling = false;
            this.btn_Salvar.AnimationSpeed = 200;
            this.btn_Salvar.AutoGenerateColors = false;
            this.btn_Salvar.BackColor = System.Drawing.Color.Transparent;
            this.btn_Salvar.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Salvar.BackgroundImage")));
            this.btn_Salvar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Salvar.ButtonText = "Salvar";
            this.btn_Salvar.ButtonTextMarginLeft = 0;
            this.btn_Salvar.ColorContrastOnClick = 45;
            this.btn_Salvar.ColorContrastOnHover = 45;
            this.btn_Salvar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_Salvar.CustomizableEdges = borderEdges2;
            this.btn_Salvar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Salvar.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_Salvar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Salvar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Salvar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Salvar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btn_Salvar.ForeColor = System.Drawing.Color.White;
            this.btn_Salvar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Salvar.IconMarginLeft = 11;
            this.btn_Salvar.IconPadding = 10;
            this.btn_Salvar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Salvar.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.IdleBorderRadius = 3;
            this.btn_Salvar.IdleBorderThickness = 1;
            this.btn_Salvar.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.IdleIconLeftImage = null;
            this.btn_Salvar.IdleIconRightImage = null;
            this.btn_Salvar.IndicateFocus = false;
            this.btn_Salvar.Location = new System.Drawing.Point(744, 612);
            this.btn_Salvar.Margin = new System.Windows.Forms.Padding(4);
            this.btn_Salvar.Name = "btn_Salvar";
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.BorderRadius = 3;
            stateProperties11.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties11.BorderThickness = 1;
            stateProperties11.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.ForeColor = System.Drawing.Color.White;
            stateProperties11.IconLeftImage = null;
            stateProperties11.IconRightImage = null;
            this.btn_Salvar.onHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties12.BorderRadius = 3;
            stateProperties12.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties12.BorderThickness = 1;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.IconLeftImage = null;
            stateProperties12.IconRightImage = null;
            this.btn_Salvar.OnPressedState = stateProperties12;
            this.btn_Salvar.Size = new System.Drawing.Size(79, 43);
            this.btn_Salvar.TabIndex = 31;
            this.btn_Salvar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Salvar.TextMarginLeft = 0;
            this.btn_Salvar.UseDefaultRadiusAndThickness = true;
            // 
            // lblEndereco
            // 
            this.lblEndereco.AutoSize = true;
            this.lblEndereco.Location = new System.Drawing.Point(49, 377);
            this.lblEndereco.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblEndereco.Name = "lblEndereco";
            this.lblEndereco.Size = new System.Drawing.Size(69, 17);
            this.lblEndereco.TabIndex = 20;
            this.lblEndereco.Text = "Endereço";
            // 
            // TextBoxEmail
            // 
            this.TextBoxEmail.AcceptsReturn = false;
            this.TextBoxEmail.AcceptsTab = false;
            this.TextBoxEmail.AnimationSpeed = 200;
            this.TextBoxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxEmail.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxEmail.BackgroundImage")));
            this.TextBoxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxEmail.BorderRadius = 1;
            this.TextBoxEmail.BorderThickness = 1;
            this.TextBoxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxEmail.DefaultText = "";
            this.TextBoxEmail.FillColor = System.Drawing.Color.White;
            this.TextBoxEmail.HideSelection = true;
            this.TextBoxEmail.IconLeft = null;
            this.TextBoxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.IconPadding = 10;
            this.TextBoxEmail.IconRight = null;
            this.TextBoxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.Lines = new string[0];
            this.TextBoxEmail.Location = new System.Drawing.Point(128, 512);
            this.TextBoxEmail.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxEmail.MaxLength = 32767;
            this.TextBoxEmail.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxEmail.Modified = false;
            this.TextBoxEmail.Multiline = false;
            this.TextBoxEmail.Name = "TextBoxEmail";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnIdleState = stateProperties16;
            this.TextBoxEmail.PasswordChar = '\0';
            this.TextBoxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.PlaceholderText = "";
            this.TextBoxEmail.ReadOnly = false;
            this.TextBoxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxEmail.SelectedText = "";
            this.TextBoxEmail.SelectionLength = 0;
            this.TextBoxEmail.SelectionStart = 0;
            this.TextBoxEmail.ShortcutsEnabled = true;
            this.TextBoxEmail.Size = new System.Drawing.Size(516, 43);
            this.TextBoxEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxEmail.TabIndex = 19;
            this.TextBoxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxEmail.TextMarginBottom = 0;
            this.TextBoxEmail.TextMarginLeft = 5;
            this.TextBoxEmail.TextMarginTop = 0;
            this.TextBoxEmail.TextPlaceholder = "";
            this.TextBoxEmail.UseSystemPasswordChar = false;
            this.TextBoxEmail.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Location = new System.Drawing.Point(73, 523);
            this.lblEmail.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(47, 17);
            this.lblEmail.TabIndex = 18;
            this.lblEmail.Text = "E-mail";
            // 
            // TextBoxEndereco
            // 
            this.TextBoxEndereco.Location = new System.Drawing.Point(128, 373);
            this.TextBoxEndereco.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxEndereco.Name = "TextBoxEndereco";
            this.TextBoxEndereco.Size = new System.Drawing.Size(516, 106);
            this.TextBoxEndereco.TabIndex = 17;
            this.TextBoxEndereco.Text = "";
            // 
            // TextBoxCelular
            // 
            this.TextBoxCelular.AcceptsReturn = false;
            this.TextBoxCelular.AcceptsTab = false;
            this.TextBoxCelular.AnimationSpeed = 200;
            this.TextBoxCelular.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCelular.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCelular.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCelular.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCelular.BackgroundImage")));
            this.TextBoxCelular.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCelular.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCelular.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCelular.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCelular.BorderRadius = 1;
            this.TextBoxCelular.BorderThickness = 1;
            this.TextBoxCelular.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCelular.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCelular.DefaultText = "";
            this.TextBoxCelular.FillColor = System.Drawing.Color.White;
            this.TextBoxCelular.HideSelection = true;
            this.TextBoxCelular.IconLeft = null;
            this.TextBoxCelular.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.IconPadding = 10;
            this.TextBoxCelular.IconRight = null;
            this.TextBoxCelular.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.Lines = new string[0];
            this.TextBoxCelular.Location = new System.Drawing.Point(633, 89);
            this.TextBoxCelular.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxCelular.MaxLength = 32767;
            this.TextBoxCelular.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCelular.Modified = false;
            this.TextBoxCelular.Multiline = false;
            this.TextBoxCelular.Name = "TextBoxCelular";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnIdleState = stateProperties20;
            this.TextBoxCelular.PasswordChar = '\0';
            this.TextBoxCelular.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.PlaceholderText = "";
            this.TextBoxCelular.ReadOnly = false;
            this.TextBoxCelular.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCelular.SelectedText = "";
            this.TextBoxCelular.SelectionLength = 0;
            this.TextBoxCelular.SelectionStart = 0;
            this.TextBoxCelular.ShortcutsEnabled = true;
            this.TextBoxCelular.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCelular.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCelular.TabIndex = 14;
            this.TextBoxCelular.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCelular.TextMarginBottom = 0;
            this.TextBoxCelular.TextMarginLeft = 5;
            this.TextBoxCelular.TextMarginTop = 0;
            this.TextBoxCelular.TextPlaceholder = "";
            this.TextBoxCelular.UseSystemPasswordChar = false;
            this.TextBoxCelular.WordWrap = true;
            // 
            // lblCelular
            // 
            this.lblCelular.AutoSize = true;
            this.lblCelular.Location = new System.Drawing.Point(573, 101);
            this.lblCelular.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCelular.Name = "lblCelular";
            this.lblCelular.Size = new System.Drawing.Size(52, 17);
            this.lblCelular.TabIndex = 13;
            this.lblCelular.Text = "Celular";
            // 
            // TextBoxCPF
            // 
            this.TextBoxCPF.AcceptsReturn = false;
            this.TextBoxCPF.AcceptsTab = false;
            this.TextBoxCPF.AnimationSpeed = 200;
            this.TextBoxCPF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCPF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCPF.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCPF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCPF.BackgroundImage")));
            this.TextBoxCPF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCPF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCPF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCPF.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCPF.BorderRadius = 1;
            this.TextBoxCPF.BorderThickness = 1;
            this.TextBoxCPF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCPF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCPF.DefaultText = "";
            this.TextBoxCPF.FillColor = System.Drawing.Color.White;
            this.TextBoxCPF.HideSelection = true;
            this.TextBoxCPF.IconLeft = null;
            this.TextBoxCPF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.IconPadding = 10;
            this.TextBoxCPF.IconRight = null;
            this.TextBoxCPF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.Lines = new string[0];
            this.TextBoxCPF.Location = new System.Drawing.Point(128, 293);
            this.TextBoxCPF.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxCPF.MaxLength = 32767;
            this.TextBoxCPF.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCPF.Modified = false;
            this.TextBoxCPF.Multiline = false;
            this.TextBoxCPF.Name = "TextBoxCPF";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnIdleState = stateProperties24;
            this.TextBoxCPF.PasswordChar = '\0';
            this.TextBoxCPF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.PlaceholderText = "";
            this.TextBoxCPF.ReadOnly = false;
            this.TextBoxCPF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCPF.SelectedText = "";
            this.TextBoxCPF.SelectionLength = 0;
            this.TextBoxCPF.SelectionStart = 0;
            this.TextBoxCPF.ShortcutsEnabled = true;
            this.TextBoxCPF.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCPF.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCPF.TabIndex = 12;
            this.TextBoxCPF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCPF.TextMarginBottom = 0;
            this.TextBoxCPF.TextMarginLeft = 5;
            this.TextBoxCPF.TextMarginTop = 0;
            this.TextBoxCPF.TextPlaceholder = "";
            this.TextBoxCPF.UseSystemPasswordChar = false;
            this.TextBoxCPF.WordWrap = true;
            // 
            // lblCpf
            // 
            this.lblCpf.AutoSize = true;
            this.lblCpf.Location = new System.Drawing.Point(84, 308);
            this.lblCpf.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCpf.Name = "lblCpf";
            this.lblCpf.Size = new System.Drawing.Size(34, 17);
            this.lblCpf.TabIndex = 11;
            this.lblCpf.Text = "CPF";
            // 
            // TextBoxRG
            // 
            this.TextBoxRG.AcceptsReturn = false;
            this.TextBoxRG.AcceptsTab = false;
            this.TextBoxRG.AnimationSpeed = 200;
            this.TextBoxRG.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxRG.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxRG.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxRG.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxRG.BackgroundImage")));
            this.TextBoxRG.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxRG.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxRG.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxRG.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxRG.BorderRadius = 1;
            this.TextBoxRG.BorderThickness = 1;
            this.TextBoxRG.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxRG.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxRG.DefaultText = "";
            this.TextBoxRG.FillColor = System.Drawing.Color.White;
            this.TextBoxRG.HideSelection = true;
            this.TextBoxRG.IconLeft = null;
            this.TextBoxRG.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.IconPadding = 10;
            this.TextBoxRG.IconRight = null;
            this.TextBoxRG.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.Lines = new string[0];
            this.TextBoxRG.Location = new System.Drawing.Point(128, 217);
            this.TextBoxRG.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxRG.MaxLength = 32767;
            this.TextBoxRG.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxRG.Modified = false;
            this.TextBoxRG.Multiline = false;
            this.TextBoxRG.Name = "TextBoxRG";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnIdleState = stateProperties28;
            this.TextBoxRG.PasswordChar = '\0';
            this.TextBoxRG.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.PlaceholderText = "";
            this.TextBoxRG.ReadOnly = false;
            this.TextBoxRG.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxRG.SelectedText = "";
            this.TextBoxRG.SelectionLength = 0;
            this.TextBoxRG.SelectionStart = 0;
            this.TextBoxRG.ShortcutsEnabled = true;
            this.TextBoxRG.Size = new System.Drawing.Size(267, 43);
            this.TextBoxRG.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxRG.TabIndex = 10;
            this.TextBoxRG.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxRG.TextMarginBottom = 0;
            this.TextBoxRG.TextMarginLeft = 5;
            this.TextBoxRG.TextMarginTop = 0;
            this.TextBoxRG.TextPlaceholder = "";
            this.TextBoxRG.UseSystemPasswordChar = false;
            this.TextBoxRG.WordWrap = true;
            // 
            // lblRG
            // 
            this.lblRG.AutoSize = true;
            this.lblRG.Location = new System.Drawing.Point(89, 231);
            this.lblRG.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblRG.Name = "lblRG";
            this.lblRG.Size = new System.Drawing.Size(29, 17);
            this.lblRG.TabIndex = 9;
            this.lblRG.Text = "RG";
            // 
            // TextBoxTelefone
            // 
            this.TextBoxTelefone.AcceptsReturn = false;
            this.TextBoxTelefone.AcceptsTab = false;
            this.TextBoxTelefone.AnimationSpeed = 200;
            this.TextBoxTelefone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTelefone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTelefone.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxTelefone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTelefone.BackgroundImage")));
            this.TextBoxTelefone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxTelefone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxTelefone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxTelefone.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTelefone.BorderRadius = 1;
            this.TextBoxTelefone.BorderThickness = 1;
            this.TextBoxTelefone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTelefone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxTelefone.DefaultText = "";
            this.TextBoxTelefone.FillColor = System.Drawing.Color.White;
            this.TextBoxTelefone.HideSelection = true;
            this.TextBoxTelefone.IconLeft = null;
            this.TextBoxTelefone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.IconPadding = 10;
            this.TextBoxTelefone.IconRight = null;
            this.TextBoxTelefone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.Lines = new string[0];
            this.TextBoxTelefone.Location = new System.Drawing.Point(128, 148);
            this.TextBoxTelefone.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxTelefone.MaxLength = 32767;
            this.TextBoxTelefone.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxTelefone.Modified = false;
            this.TextBoxTelefone.Multiline = false;
            this.TextBoxTelefone.Name = "TextBoxTelefone";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnIdleState = stateProperties32;
            this.TextBoxTelefone.PasswordChar = '\0';
            this.TextBoxTelefone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.PlaceholderText = "";
            this.TextBoxTelefone.ReadOnly = false;
            this.TextBoxTelefone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTelefone.SelectedText = "";
            this.TextBoxTelefone.SelectionLength = 0;
            this.TextBoxTelefone.SelectionStart = 0;
            this.TextBoxTelefone.ShortcutsEnabled = true;
            this.TextBoxTelefone.Size = new System.Drawing.Size(267, 43);
            this.TextBoxTelefone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxTelefone.TabIndex = 8;
            this.TextBoxTelefone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxTelefone.TextMarginBottom = 0;
            this.TextBoxTelefone.TextMarginLeft = 5;
            this.TextBoxTelefone.TextMarginTop = 0;
            this.TextBoxTelefone.TextPlaceholder = "";
            this.TextBoxTelefone.UseSystemPasswordChar = false;
            this.TextBoxTelefone.WordWrap = true;
            // 
            // lblTelefone
            // 
            this.lblTelefone.AutoSize = true;
            this.lblTelefone.Location = new System.Drawing.Point(55, 161);
            this.lblTelefone.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblTelefone.Name = "lblTelefone";
            this.lblTelefone.Size = new System.Drawing.Size(64, 17);
            this.lblTelefone.TabIndex = 7;
            this.lblTelefone.Text = "Telefone";
            // 
            // TextBoxDataNascimento
            // 
            this.TextBoxDataNascimento.AcceptsReturn = false;
            this.TextBoxDataNascimento.AcceptsTab = false;
            this.TextBoxDataNascimento.AnimationSpeed = 200;
            this.TextBoxDataNascimento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxDataNascimento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxDataNascimento.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxDataNascimento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxDataNascimento.BackgroundImage")));
            this.TextBoxDataNascimento.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxDataNascimento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxDataNascimento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxDataNascimento.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.BorderRadius = 1;
            this.TextBoxDataNascimento.BorderThickness = 1;
            this.TextBoxDataNascimento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxDataNascimento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxDataNascimento.DefaultText = "";
            this.TextBoxDataNascimento.FillColor = System.Drawing.Color.White;
            this.TextBoxDataNascimento.HideSelection = true;
            this.TextBoxDataNascimento.IconLeft = null;
            this.TextBoxDataNascimento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.IconPadding = 10;
            this.TextBoxDataNascimento.IconRight = null;
            this.TextBoxDataNascimento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.Lines = new string[0];
            this.TextBoxDataNascimento.Location = new System.Drawing.Point(128, 89);
            this.TextBoxDataNascimento.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxDataNascimento.MaxLength = 32767;
            this.TextBoxDataNascimento.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxDataNascimento.Modified = false;
            this.TextBoxDataNascimento.Multiline = false;
            this.TextBoxDataNascimento.Name = "TextBoxDataNascimento";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnIdleState = stateProperties36;
            this.TextBoxDataNascimento.PasswordChar = '\0';
            this.TextBoxDataNascimento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.PlaceholderText = "";
            this.TextBoxDataNascimento.ReadOnly = false;
            this.TextBoxDataNascimento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxDataNascimento.SelectedText = "";
            this.TextBoxDataNascimento.SelectionLength = 0;
            this.TextBoxDataNascimento.SelectionStart = 0;
            this.TextBoxDataNascimento.ShortcutsEnabled = true;
            this.TextBoxDataNascimento.Size = new System.Drawing.Size(189, 43);
            this.TextBoxDataNascimento.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxDataNascimento.TabIndex = 6;
            this.TextBoxDataNascimento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxDataNascimento.TextMarginBottom = 0;
            this.TextBoxDataNascimento.TextMarginLeft = 5;
            this.TextBoxDataNascimento.TextMarginTop = 0;
            this.TextBoxDataNascimento.TextPlaceholder = "";
            this.TextBoxDataNascimento.UseSystemPasswordChar = false;
            this.TextBoxDataNascimento.WordWrap = true;
            // 
            // lblNome
            // 
            this.lblNome.AutoSize = true;
            this.lblNome.Location = new System.Drawing.Point(73, 33);
            this.lblNome.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblNome.Name = "lblNome";
            this.lblNome.Size = new System.Drawing.Size(45, 17);
            this.lblNome.TabIndex = 5;
            this.lblNome.Text = "Nome";
            // 
            // TextBoxSexo
            // 
            this.TextBoxSexo.AcceptsReturn = false;
            this.TextBoxSexo.AcceptsTab = false;
            this.TextBoxSexo.AnimationSpeed = 200;
            this.TextBoxSexo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxSexo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxSexo.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxSexo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxSexo.BackgroundImage")));
            this.TextBoxSexo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxSexo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxSexo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxSexo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxSexo.BorderRadius = 1;
            this.TextBoxSexo.BorderThickness = 1;
            this.TextBoxSexo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxSexo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxSexo.DefaultText = "";
            this.TextBoxSexo.FillColor = System.Drawing.Color.White;
            this.TextBoxSexo.HideSelection = true;
            this.TextBoxSexo.IconLeft = null;
            this.TextBoxSexo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.IconPadding = 10;
            this.TextBoxSexo.IconRight = null;
            this.TextBoxSexo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.Lines = new string[0];
            this.TextBoxSexo.Location = new System.Drawing.Point(633, 21);
            this.TextBoxSexo.Margin = new System.Windows.Forms.Padding(4);
            this.TextBoxSexo.MaxLength = 32767;
            this.TextBoxSexo.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxSexo.Modified = false;
            this.TextBoxSexo.Multiline = false;
            this.TextBoxSexo.Name = "TextBoxSexo";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Empty;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnIdleState = stateProperties40;
            this.TextBoxSexo.PasswordChar = '\0';
            this.TextBoxSexo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.PlaceholderText = "";
            this.TextBoxSexo.ReadOnly = false;
            this.TextBoxSexo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxSexo.SelectedText = "";
            this.TextBoxSexo.SelectionLength = 0;
            this.TextBoxSexo.SelectionStart = 0;
            this.TextBoxSexo.ShortcutsEnabled = true;
            this.TextBoxSexo.Size = new System.Drawing.Size(140, 43);
            this.TextBoxSexo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxSexo.TabIndex = 2;
            this.TextBoxSexo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxSexo.TextMarginBottom = 0;
            this.TextBoxSexo.TextMarginLeft = 5;
            this.TextBoxSexo.TextMarginTop = 0;
            this.TextBoxSexo.TextPlaceholder = "";
            this.TextBoxSexo.UseSystemPasswordChar = false;
            this.TextBoxSexo.WordWrap = true;
            // 
            // frmCadastro_funcionario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ClientSize = new System.Drawing.Size(1081, 772);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "frmCadastro_funcionario";
            this.Text = "Cadastro De Cliente";
            this.Load += new System.EventHandler(this.Form_Cadastro_Cliente_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuCustomLabel lblSexo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxNome;
        private Bunifu.Framework.UI.BunifuCustomLabel lblDataNascimento;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxEmail;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEmail;
        private System.Windows.Forms.RichTextBox TextBoxEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCelular;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCelular;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCPF;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCpf;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxRG;
        private Bunifu.Framework.UI.BunifuCustomLabel lblRG;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxTelefone;
        private Bunifu.Framework.UI.BunifuCustomLabel lblTelefone;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxDataNascimento;
        private Bunifu.Framework.UI.BunifuCustomLabel lblNome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Sair_ENTREGAS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Salvar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCNH;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCnh;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxSexo;
    }
}