namespace PIM.View
{
    partial class frmCadastro_funcionario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCadastro_funcionario));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.lblSexo = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxSexo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextBoxNome = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblDataNascimento = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.TextBoxCNH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCnh = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btn_Sair_ENTREGAS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_Salvar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblEndereco = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblEmail = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEndereco = new System.Windows.Forms.RichTextBox();
            this.TextBoxCelular = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCelular = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxCPF = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCpf = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxRG = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblRG = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxTelefone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblTelefone = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxDataNascimento = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblNome = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblSexo
            // 
            this.lblSexo.AutoSize = true;
            this.lblSexo.Location = new System.Drawing.Point(584, 33);
            this.lblSexo.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblSexo.Name = "lblSexo";
            this.lblSexo.Size = new System.Drawing.Size(39, 17);
            this.lblSexo.TabIndex = 0;
            this.lblSexo.Text = "Sexo";
            // 
            // TextBoxSexo
            // 
            this.TextBoxSexo.AcceptsReturn = false;
            this.TextBoxSexo.AcceptsTab = false;
            this.TextBoxSexo.AnimationSpeed = 200;
            this.TextBoxSexo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxSexo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxSexo.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxSexo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxSexo.BackgroundImage")));
            this.TextBoxSexo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxSexo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxSexo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxSexo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxSexo.BorderRadius = 1;
            this.TextBoxSexo.BorderThickness = 1;
            this.TextBoxSexo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxSexo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxSexo.DefaultText = "";
            this.TextBoxSexo.FillColor = System.Drawing.Color.White;
            this.TextBoxSexo.HideSelection = true;
            this.TextBoxSexo.IconLeft = null;
            this.TextBoxSexo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.IconPadding = 10;
            this.TextBoxSexo.IconRight = null;
            this.TextBoxSexo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.Lines = new string[0];
            this.TextBoxSexo.Location = new System.Drawing.Point(633, 21);
            this.TextBoxSexo.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxSexo.MaxLength = 32767;
            this.TextBoxSexo.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxSexo.Modified = false;
            this.TextBoxSexo.Multiline = false;
            this.TextBoxSexo.Name = "TextBoxSexo";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Empty;
            stateProperties42.FillColor = System.Drawing.Color.White;
            stateProperties42.ForeColor = System.Drawing.Color.Empty;
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnIdleState = stateProperties44;
            this.TextBoxSexo.PasswordChar = '\0';
            this.TextBoxSexo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.PlaceholderText = "";
            this.TextBoxSexo.ReadOnly = false;
            this.TextBoxSexo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxSexo.SelectedText = "";
            this.TextBoxSexo.SelectionLength = 0;
            this.TextBoxSexo.SelectionStart = 0;
            this.TextBoxSexo.ShortcutsEnabled = true;
            this.TextBoxSexo.Size = new System.Drawing.Size(140, 43);
            this.TextBoxSexo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxSexo.TabIndex = 2;
            this.TextBoxSexo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxSexo.TextMarginBottom = 0;
            this.TextBoxSexo.TextMarginLeft = 5;
            this.TextBoxSexo.TextMarginTop = 0;
            this.TextBoxSexo.TextPlaceholder = "";
            this.TextBoxSexo.UseSystemPasswordChar = false;
            this.TextBoxSexo.WordWrap = true;
            // 
            // TextBoxNome
            // 
            this.TextBoxNome.AcceptsReturn = false;
            this.TextBoxNome.AcceptsTab = false;
            this.TextBoxNome.AnimationSpeed = 200;
            this.TextBoxNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxNome.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxNome.BackgroundImage")));
            this.TextBoxNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxNome.BorderRadius = 1;
            this.TextBoxNome.BorderThickness = 1;
            this.TextBoxNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxNome.DefaultText = "";
            this.TextBoxNome.FillColor = System.Drawing.Color.White;
            this.TextBoxNome.HideSelection = true;
            this.TextBoxNome.IconLeft = null;
            this.TextBoxNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.IconPadding = 10;
            this.TextBoxNome.IconRight = null;
            this.TextBoxNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.Lines = new string[0];
            this.TextBoxNome.Location = new System.Drawing.Point(128, 21);
            this.TextBoxNome.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxNome.MaxLength = 32767;
            this.TextBoxNome.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxNome.Modified = false;
            this.TextBoxNome.Multiline = false;
            this.TextBoxNome.Name = "TextBoxNome";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Empty;
            stateProperties46.FillColor = System.Drawing.Color.White;
            stateProperties46.ForeColor = System.Drawing.Color.Empty;
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnIdleState = stateProperties48;
            this.TextBoxNome.PasswordChar = '\0';
            this.TextBoxNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.PlaceholderText = "";
            this.TextBoxNome.ReadOnly = false;
            this.TextBoxNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxNome.SelectedText = "";
            this.TextBoxNome.SelectionLength = 0;
            this.TextBoxNome.SelectionStart = 0;
            this.TextBoxNome.ShortcutsEnabled = true;
            this.TextBoxNome.Size = new System.Drawing.Size(311, 43);
            this.TextBoxNome.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxNome.TabIndex = 4;
            this.TextBoxNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxNome.TextMarginBottom = 0;
            this.TextBoxNome.TextMarginLeft = 5;
            this.TextBoxNome.TextMarginTop = 0;
            this.TextBoxNome.TextPlaceholder = "";
            this.TextBoxNome.UseSystemPasswordChar = false;
            this.TextBoxNome.WordWrap = true;
            this.TextBoxNome.TextChanged += new System.EventHandler(this.TextBoxNome_TextChanged);
            // 
            // lblDataNascimento
            // 
            this.lblDataNascimento.AutoSize = true;
            this.lblDataNascimento.Location = new System.Drawing.Point(39, 101);
            this.lblDataNascimento.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblDataNascimento.Name = "lblDataNascimento";
            this.lblDataNascimento.Size = new System.Drawing.Size(78, 17);
            this.lblDataNascimento.TabIndex = 3;
            this.lblDataNascimento.Text = "Data Nasc.";
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.BackColor = System.Drawing.Color.Black;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(16, 31);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(279, 31);
            this.bunifuLabel1.TabIndex = 6;
            this.bunifuLabel1.Text = "Cadastro de Funcionario";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCNH);
            this.bunifuShadowPanel1.Controls.Add(this.lblCnh);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Sair_ENTREGAS);
            this.bunifuShadowPanel1.Controls.Add(this.btn_Salvar);
            this.bunifuShadowPanel1.Controls.Add(this.lblEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEmail);
            this.bunifuShadowPanel1.Controls.Add(this.lblEmail);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCelular);
            this.bunifuShadowPanel1.Controls.Add(this.lblCelular);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCPF);
            this.bunifuShadowPanel1.Controls.Add(this.lblCpf);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxRG);
            this.bunifuShadowPanel1.Controls.Add(this.lblRG);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.lblTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxDataNascimento);
            this.bunifuShadowPanel1.Controls.Add(this.lblNome);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxSexo);
            this.bunifuShadowPanel1.Controls.Add(this.lblSexo);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxNome);
            this.bunifuShadowPanel1.Controls.Add(this.lblDataNascimento);
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(16, 71);
            this.bunifuShadowPanel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(1049, 686);
            this.bunifuShadowPanel1.TabIndex = 8;
            // 
            // TextBoxCNH
            // 
            this.TextBoxCNH.AcceptsReturn = false;
            this.TextBoxCNH.AcceptsTab = false;
            this.TextBoxCNH.AnimationSpeed = 200;
            this.TextBoxCNH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCNH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCNH.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCNH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCNH.BackgroundImage")));
            this.TextBoxCNH.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCNH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCNH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCNH.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCNH.BorderRadius = 1;
            this.TextBoxCNH.BorderThickness = 1;
            this.TextBoxCNH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCNH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCNH.DefaultText = "";
            this.TextBoxCNH.FillColor = System.Drawing.Color.White;
            this.TextBoxCNH.HideSelection = true;
            this.TextBoxCNH.IconLeft = null;
            this.TextBoxCNH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.IconPadding = 10;
            this.TextBoxCNH.IconRight = null;
            this.TextBoxCNH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.Lines = new string[0];
            this.TextBoxCNH.Location = new System.Drawing.Point(633, 161);
            this.TextBoxCNH.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxCNH.MaxLength = 32767;
            this.TextBoxCNH.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCNH.Modified = false;
            this.TextBoxCNH.Multiline = false;
            this.TextBoxCNH.Name = "TextBoxCNH";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.Empty;
            stateProperties50.FillColor = System.Drawing.Color.White;
            stateProperties50.ForeColor = System.Drawing.Color.Empty;
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnIdleState = stateProperties52;
            this.TextBoxCNH.PasswordChar = '\0';
            this.TextBoxCNH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.PlaceholderText = "";
            this.TextBoxCNH.ReadOnly = false;
            this.TextBoxCNH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCNH.SelectedText = "";
            this.TextBoxCNH.SelectionLength = 0;
            this.TextBoxCNH.SelectionStart = 0;
            this.TextBoxCNH.ShortcutsEnabled = true;
            this.TextBoxCNH.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCNH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCNH.TabIndex = 33;
            this.TextBoxCNH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCNH.TextMarginBottom = 0;
            this.TextBoxCNH.TextMarginLeft = 5;
            this.TextBoxCNH.TextMarginTop = 0;
            this.TextBoxCNH.TextPlaceholder = "";
            this.TextBoxCNH.UseSystemPasswordChar = false;
            this.TextBoxCNH.WordWrap = true;
            // 
            // lblCnh
            // 
            this.lblCnh.AutoSize = true;
            this.lblCnh.Location = new System.Drawing.Point(584, 174);
            this.lblCnh.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCnh.Name = "lblCnh";
            this.lblCnh.Size = new System.Drawing.Size(37, 17);
            this.lblCnh.TabIndex = 32;
            this.lblCnh.Text = "CNH";
            // 
            // btn_Sair_ENTREGAS
            // 
            this.btn_Sair_ENTREGAS.AllowToggling = false;
            this.btn_Sair_ENTREGAS.AnimationSpeed = 200;
            this.btn_Sair_ENTREGAS.AutoGenerateColors = false;
            this.btn_Sair_ENTREGAS.BackColor = System.Drawing.Color.Transparent;
            this.btn_Sair_ENTREGAS.BackColor1 = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Sair_ENTREGAS.BackgroundImage")));
            this.btn_Sair_ENTREGAS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Sair_ENTREGAS.ButtonText = "Sair";
            this.btn_Sair_ENTREGAS.ButtonTextMarginLeft = 0;
            this.btn_Sair_ENTREGAS.ColorContrastOnClick = 45;
            this.btn_Sair_ENTREGAS.ColorContrastOnHover = 45;
            this.btn_Sair_ENTREGAS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_Sair_ENTREGAS.CustomizableEdges = borderEdges3;
            this.btn_Sair_ENTREGAS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Sair_ENTREGAS.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_Sair_ENTREGAS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Sair_ENTREGAS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Sair_ENTREGAS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Sair_ENTREGAS.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btn_Sair_ENTREGAS.ForeColor = System.Drawing.Color.White;
            this.btn_Sair_ENTREGAS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Sair_ENTREGAS.IconMarginLeft = 11;
            this.btn_Sair_ENTREGAS.IconPadding = 10;
            this.btn_Sair_ENTREGAS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Sair_ENTREGAS.IdleBorderColor = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.IdleBorderRadius = 3;
            this.btn_Sair_ENTREGAS.IdleBorderThickness = 1;
            this.btn_Sair_ENTREGAS.IdleFillColor = System.Drawing.Color.Gray;
            this.btn_Sair_ENTREGAS.IdleIconLeftImage = null;
            this.btn_Sair_ENTREGAS.IdleIconRightImage = null;
            this.btn_Sair_ENTREGAS.IndicateFocus = false;
            this.btn_Sair_ENTREGAS.Location = new System.Drawing.Point(931, 612);
            this.btn_Sair_ENTREGAS.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btn_Sair_ENTREGAS.Name = "btn_Sair_ENTREGAS";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties53.BorderRadius = 3;
            stateProperties53.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties53.BorderThickness = 1;
            stateProperties53.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties53.ForeColor = System.Drawing.Color.White;
            stateProperties53.IconLeftImage = null;
            stateProperties53.IconRightImage = null;
            this.btn_Sair_ENTREGAS.onHoverState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties54.BorderRadius = 3;
            stateProperties54.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties54.BorderThickness = 1;
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties54.ForeColor = System.Drawing.Color.White;
            stateProperties54.IconLeftImage = null;
            stateProperties54.IconRightImage = null;
            this.btn_Sair_ENTREGAS.OnPressedState = stateProperties54;
            this.btn_Sair_ENTREGAS.Size = new System.Drawing.Size(79, 43);
            this.btn_Sair_ENTREGAS.TabIndex = 30;
            this.btn_Sair_ENTREGAS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Sair_ENTREGAS.TextMarginLeft = 0;
            this.btn_Sair_ENTREGAS.UseDefaultRadiusAndThickness = true;
            // 
            // btn_Salvar
            // 
            this.btn_Salvar.AllowToggling = false;
            this.btn_Salvar.AnimationSpeed = 200;
            this.btn_Salvar.AutoGenerateColors = false;
            this.btn_Salvar.BackColor = System.Drawing.Color.Transparent;
            this.btn_Salvar.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_Salvar.BackgroundImage")));
            this.btn_Salvar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_Salvar.ButtonText = "Salvar";
            this.btn_Salvar.ButtonTextMarginLeft = 0;
            this.btn_Salvar.ColorContrastOnClick = 45;
            this.btn_Salvar.ColorContrastOnHover = 45;
            this.btn_Salvar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_Salvar.CustomizableEdges = borderEdges4;
            this.btn_Salvar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_Salvar.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_Salvar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_Salvar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_Salvar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_Salvar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btn_Salvar.ForeColor = System.Drawing.Color.White;
            this.btn_Salvar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Salvar.IconMarginLeft = 11;
            this.btn_Salvar.IconPadding = 10;
            this.btn_Salvar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_Salvar.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.IdleBorderRadius = 3;
            this.btn_Salvar.IdleBorderThickness = 1;
            this.btn_Salvar.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btn_Salvar.IdleIconLeftImage = null;
            this.btn_Salvar.IdleIconRightImage = null;
            this.btn_Salvar.IndicateFocus = false;
            this.btn_Salvar.Location = new System.Drawing.Point(744, 612);
            this.btn_Salvar.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btn_Salvar.Name = "btn_Salvar";
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.BorderRadius = 3;
            stateProperties55.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties55.BorderThickness = 1;
            stateProperties55.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.ForeColor = System.Drawing.Color.White;
            stateProperties55.IconLeftImage = null;
            stateProperties55.IconRightImage = null;
            this.btn_Salvar.onHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties56.BorderRadius = 3;
            stateProperties56.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties56.BorderThickness = 1;
            stateProperties56.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties56.ForeColor = System.Drawing.Color.White;
            stateProperties56.IconLeftImage = null;
            stateProperties56.IconRightImage = null;
            this.btn_Salvar.OnPressedState = stateProperties56;
            this.btn_Salvar.Size = new System.Drawing.Size(79, 43);
            this.btn_Salvar.TabIndex = 31;
            this.btn_Salvar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_Salvar.TextMarginLeft = 0;
            this.btn_Salvar.UseDefaultRadiusAndThickness = true;
            // 
            // lblEndereco
            // 
            this.lblEndereco.AutoSize = true;
            this.lblEndereco.Location = new System.Drawing.Point(49, 377);
            this.lblEndereco.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblEndereco.Name = "lblEndereco";
            this.lblEndereco.Size = new System.Drawing.Size(69, 17);
            this.lblEndereco.TabIndex = 20;
            this.lblEndereco.Text = "Endereço";
            // 
            // TextBoxEmail
            // 
            this.TextBoxEmail.AcceptsReturn = false;
            this.TextBoxEmail.AcceptsTab = false;
            this.TextBoxEmail.AnimationSpeed = 200;
            this.TextBoxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxEmail.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxEmail.BackgroundImage")));
            this.TextBoxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxEmail.BorderRadius = 1;
            this.TextBoxEmail.BorderThickness = 1;
            this.TextBoxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxEmail.DefaultText = "";
            this.TextBoxEmail.FillColor = System.Drawing.Color.White;
            this.TextBoxEmail.HideSelection = true;
            this.TextBoxEmail.IconLeft = null;
            this.TextBoxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.IconPadding = 10;
            this.TextBoxEmail.IconRight = null;
            this.TextBoxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.Lines = new string[0];
            this.TextBoxEmail.Location = new System.Drawing.Point(128, 512);
            this.TextBoxEmail.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxEmail.MaxLength = 32767;
            this.TextBoxEmail.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxEmail.Modified = false;
            this.TextBoxEmail.Multiline = false;
            this.TextBoxEmail.Name = "TextBoxEmail";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.Empty;
            stateProperties58.FillColor = System.Drawing.Color.White;
            stateProperties58.ForeColor = System.Drawing.Color.Empty;
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnIdleState = stateProperties60;
            this.TextBoxEmail.PasswordChar = '\0';
            this.TextBoxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.PlaceholderText = "";
            this.TextBoxEmail.ReadOnly = false;
            this.TextBoxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxEmail.SelectedText = "";
            this.TextBoxEmail.SelectionLength = 0;
            this.TextBoxEmail.SelectionStart = 0;
            this.TextBoxEmail.ShortcutsEnabled = true;
            this.TextBoxEmail.Size = new System.Drawing.Size(516, 43);
            this.TextBoxEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxEmail.TabIndex = 19;
            this.TextBoxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxEmail.TextMarginBottom = 0;
            this.TextBoxEmail.TextMarginLeft = 5;
            this.TextBoxEmail.TextMarginTop = 0;
            this.TextBoxEmail.TextPlaceholder = "";
            this.TextBoxEmail.UseSystemPasswordChar = false;
            this.TextBoxEmail.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Location = new System.Drawing.Point(73, 523);
            this.lblEmail.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(47, 17);
            this.lblEmail.TabIndex = 18;
            this.lblEmail.Text = "E-mail";
            // 
            // TextBoxEndereco
            // 
            this.TextBoxEndereco.Location = new System.Drawing.Point(128, 373);
            this.TextBoxEndereco.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxEndereco.Name = "TextBoxEndereco";
            this.TextBoxEndereco.Size = new System.Drawing.Size(516, 106);
            this.TextBoxEndereco.TabIndex = 17;
            this.TextBoxEndereco.Text = "";
            // 
            // TextBoxCelular
            // 
            this.TextBoxCelular.AcceptsReturn = false;
            this.TextBoxCelular.AcceptsTab = false;
            this.TextBoxCelular.AnimationSpeed = 200;
            this.TextBoxCelular.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCelular.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCelular.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCelular.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCelular.BackgroundImage")));
            this.TextBoxCelular.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCelular.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCelular.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCelular.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCelular.BorderRadius = 1;
            this.TextBoxCelular.BorderThickness = 1;
            this.TextBoxCelular.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCelular.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCelular.DefaultText = "";
            this.TextBoxCelular.FillColor = System.Drawing.Color.White;
            this.TextBoxCelular.HideSelection = true;
            this.TextBoxCelular.IconLeft = null;
            this.TextBoxCelular.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.IconPadding = 10;
            this.TextBoxCelular.IconRight = null;
            this.TextBoxCelular.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.Lines = new string[0];
            this.TextBoxCelular.Location = new System.Drawing.Point(633, 89);
            this.TextBoxCelular.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxCelular.MaxLength = 32767;
            this.TextBoxCelular.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCelular.Modified = false;
            this.TextBoxCelular.Multiline = false;
            this.TextBoxCelular.Name = "TextBoxCelular";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.Empty;
            stateProperties62.FillColor = System.Drawing.Color.White;
            stateProperties62.ForeColor = System.Drawing.Color.Empty;
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnIdleState = stateProperties64;
            this.TextBoxCelular.PasswordChar = '\0';
            this.TextBoxCelular.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.PlaceholderText = "";
            this.TextBoxCelular.ReadOnly = false;
            this.TextBoxCelular.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCelular.SelectedText = "";
            this.TextBoxCelular.SelectionLength = 0;
            this.TextBoxCelular.SelectionStart = 0;
            this.TextBoxCelular.ShortcutsEnabled = true;
            this.TextBoxCelular.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCelular.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCelular.TabIndex = 14;
            this.TextBoxCelular.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCelular.TextMarginBottom = 0;
            this.TextBoxCelular.TextMarginLeft = 5;
            this.TextBoxCelular.TextMarginTop = 0;
            this.TextBoxCelular.TextPlaceholder = "";
            this.TextBoxCelular.UseSystemPasswordChar = false;
            this.TextBoxCelular.WordWrap = true;
            // 
            // lblCelular
            // 
            this.lblCelular.AutoSize = true;
            this.lblCelular.Location = new System.Drawing.Point(573, 101);
            this.lblCelular.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCelular.Name = "lblCelular";
            this.lblCelular.Size = new System.Drawing.Size(52, 17);
            this.lblCelular.TabIndex = 13;
            this.lblCelular.Text = "Celular";
            // 
            // TextBoxCPF
            // 
            this.TextBoxCPF.AcceptsReturn = false;
            this.TextBoxCPF.AcceptsTab = false;
            this.TextBoxCPF.AnimationSpeed = 200;
            this.TextBoxCPF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCPF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCPF.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCPF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCPF.BackgroundImage")));
            this.TextBoxCPF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCPF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCPF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCPF.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCPF.BorderRadius = 1;
            this.TextBoxCPF.BorderThickness = 1;
            this.TextBoxCPF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCPF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCPF.DefaultText = "";
            this.TextBoxCPF.FillColor = System.Drawing.Color.White;
            this.TextBoxCPF.HideSelection = true;
            this.TextBoxCPF.IconLeft = null;
            this.TextBoxCPF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.IconPadding = 10;
            this.TextBoxCPF.IconRight = null;
            this.TextBoxCPF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.Lines = new string[0];
            this.TextBoxCPF.Location = new System.Drawing.Point(128, 293);
            this.TextBoxCPF.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxCPF.MaxLength = 32767;
            this.TextBoxCPF.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxCPF.Modified = false;
            this.TextBoxCPF.Multiline = false;
            this.TextBoxCPF.Name = "TextBoxCPF";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.Empty;
            stateProperties66.FillColor = System.Drawing.Color.White;
            stateProperties66.ForeColor = System.Drawing.Color.Empty;
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnIdleState = stateProperties68;
            this.TextBoxCPF.PasswordChar = '\0';
            this.TextBoxCPF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.PlaceholderText = "";
            this.TextBoxCPF.ReadOnly = false;
            this.TextBoxCPF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCPF.SelectedText = "";
            this.TextBoxCPF.SelectionLength = 0;
            this.TextBoxCPF.SelectionStart = 0;
            this.TextBoxCPF.ShortcutsEnabled = true;
            this.TextBoxCPF.Size = new System.Drawing.Size(267, 43);
            this.TextBoxCPF.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCPF.TabIndex = 12;
            this.TextBoxCPF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCPF.TextMarginBottom = 0;
            this.TextBoxCPF.TextMarginLeft = 5;
            this.TextBoxCPF.TextMarginTop = 0;
            this.TextBoxCPF.TextPlaceholder = "";
            this.TextBoxCPF.UseSystemPasswordChar = false;
            this.TextBoxCPF.WordWrap = true;
            // 
            // lblCpf
            // 
            this.lblCpf.AutoSize = true;
            this.lblCpf.Location = new System.Drawing.Point(84, 308);
            this.lblCpf.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCpf.Name = "lblCpf";
            this.lblCpf.Size = new System.Drawing.Size(34, 17);
            this.lblCpf.TabIndex = 11;
            this.lblCpf.Text = "CPF";
            // 
            // TextBoxRG
            // 
            this.TextBoxRG.AcceptsReturn = false;
            this.TextBoxRG.AcceptsTab = false;
            this.TextBoxRG.AnimationSpeed = 200;
            this.TextBoxRG.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxRG.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxRG.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxRG.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxRG.BackgroundImage")));
            this.TextBoxRG.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxRG.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxRG.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxRG.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxRG.BorderRadius = 1;
            this.TextBoxRG.BorderThickness = 1;
            this.TextBoxRG.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxRG.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxRG.DefaultText = "";
            this.TextBoxRG.FillColor = System.Drawing.Color.White;
            this.TextBoxRG.HideSelection = true;
            this.TextBoxRG.IconLeft = null;
            this.TextBoxRG.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.IconPadding = 10;
            this.TextBoxRG.IconRight = null;
            this.TextBoxRG.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.Lines = new string[0];
            this.TextBoxRG.Location = new System.Drawing.Point(128, 217);
            this.TextBoxRG.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxRG.MaxLength = 32767;
            this.TextBoxRG.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxRG.Modified = false;
            this.TextBoxRG.Multiline = false;
            this.TextBoxRG.Name = "TextBoxRG";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.Empty;
            stateProperties70.FillColor = System.Drawing.Color.White;
            stateProperties70.ForeColor = System.Drawing.Color.Empty;
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnIdleState = stateProperties72;
            this.TextBoxRG.PasswordChar = '\0';
            this.TextBoxRG.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.PlaceholderText = "";
            this.TextBoxRG.ReadOnly = false;
            this.TextBoxRG.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxRG.SelectedText = "";
            this.TextBoxRG.SelectionLength = 0;
            this.TextBoxRG.SelectionStart = 0;
            this.TextBoxRG.ShortcutsEnabled = true;
            this.TextBoxRG.Size = new System.Drawing.Size(267, 43);
            this.TextBoxRG.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxRG.TabIndex = 10;
            this.TextBoxRG.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxRG.TextMarginBottom = 0;
            this.TextBoxRG.TextMarginLeft = 5;
            this.TextBoxRG.TextMarginTop = 0;
            this.TextBoxRG.TextPlaceholder = "";
            this.TextBoxRG.UseSystemPasswordChar = false;
            this.TextBoxRG.WordWrap = true;
            // 
            // lblRG
            // 
            this.lblRG.AutoSize = true;
            this.lblRG.Location = new System.Drawing.Point(89, 231);
            this.lblRG.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblRG.Name = "lblRG";
            this.lblRG.Size = new System.Drawing.Size(29, 17);
            this.lblRG.TabIndex = 9;
            this.lblRG.Text = "RG";
            // 
            // TextBoxTelefone
            // 
            this.TextBoxTelefone.AcceptsReturn = false;
            this.TextBoxTelefone.AcceptsTab = false;
            this.TextBoxTelefone.AnimationSpeed = 200;
            this.TextBoxTelefone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTelefone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTelefone.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxTelefone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTelefone.BackgroundImage")));
            this.TextBoxTelefone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxTelefone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxTelefone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxTelefone.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTelefone.BorderRadius = 1;
            this.TextBoxTelefone.BorderThickness = 1;
            this.TextBoxTelefone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTelefone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxTelefone.DefaultText = "";
            this.TextBoxTelefone.FillColor = System.Drawing.Color.White;
            this.TextBoxTelefone.HideSelection = true;
            this.TextBoxTelefone.IconLeft = null;
            this.TextBoxTelefone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.IconPadding = 10;
            this.TextBoxTelefone.IconRight = null;
            this.TextBoxTelefone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.Lines = new string[0];
            this.TextBoxTelefone.Location = new System.Drawing.Point(128, 148);
            this.TextBoxTelefone.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxTelefone.MaxLength = 32767;
            this.TextBoxTelefone.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxTelefone.Modified = false;
            this.TextBoxTelefone.Multiline = false;
            this.TextBoxTelefone.Name = "TextBoxTelefone";
            stateProperties73.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.Color.Empty;
            stateProperties74.FillColor = System.Drawing.Color.White;
            stateProperties74.ForeColor = System.Drawing.Color.Empty;
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.Silver;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnIdleState = stateProperties76;
            this.TextBoxTelefone.PasswordChar = '\0';
            this.TextBoxTelefone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.PlaceholderText = "";
            this.TextBoxTelefone.ReadOnly = false;
            this.TextBoxTelefone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTelefone.SelectedText = "";
            this.TextBoxTelefone.SelectionLength = 0;
            this.TextBoxTelefone.SelectionStart = 0;
            this.TextBoxTelefone.ShortcutsEnabled = true;
            this.TextBoxTelefone.Size = new System.Drawing.Size(267, 43);
            this.TextBoxTelefone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxTelefone.TabIndex = 8;
            this.TextBoxTelefone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxTelefone.TextMarginBottom = 0;
            this.TextBoxTelefone.TextMarginLeft = 5;
            this.TextBoxTelefone.TextMarginTop = 0;
            this.TextBoxTelefone.TextPlaceholder = "";
            this.TextBoxTelefone.UseSystemPasswordChar = false;
            this.TextBoxTelefone.WordWrap = true;
            // 
            // lblTelefone
            // 
            this.lblTelefone.AutoSize = true;
            this.lblTelefone.Location = new System.Drawing.Point(55, 161);
            this.lblTelefone.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblTelefone.Name = "lblTelefone";
            this.lblTelefone.Size = new System.Drawing.Size(64, 17);
            this.lblTelefone.TabIndex = 7;
            this.lblTelefone.Text = "Telefone";
            // 
            // TextBoxDataNascimento
            // 
            this.TextBoxDataNascimento.AcceptsReturn = false;
            this.TextBoxDataNascimento.AcceptsTab = false;
            this.TextBoxDataNascimento.AnimationSpeed = 200;
            this.TextBoxDataNascimento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxDataNascimento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxDataNascimento.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxDataNascimento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxDataNascimento.BackgroundImage")));
            this.TextBoxDataNascimento.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxDataNascimento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxDataNascimento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxDataNascimento.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.BorderRadius = 1;
            this.TextBoxDataNascimento.BorderThickness = 1;
            this.TextBoxDataNascimento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxDataNascimento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxDataNascimento.DefaultText = "";
            this.TextBoxDataNascimento.FillColor = System.Drawing.Color.White;
            this.TextBoxDataNascimento.HideSelection = true;
            this.TextBoxDataNascimento.IconLeft = null;
            this.TextBoxDataNascimento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.IconPadding = 10;
            this.TextBoxDataNascimento.IconRight = null;
            this.TextBoxDataNascimento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.Lines = new string[0];
            this.TextBoxDataNascimento.Location = new System.Drawing.Point(128, 89);
            this.TextBoxDataNascimento.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.TextBoxDataNascimento.MaxLength = 32767;
            this.TextBoxDataNascimento.MinimumSize = new System.Drawing.Size(133, 43);
            this.TextBoxDataNascimento.Modified = false;
            this.TextBoxDataNascimento.Multiline = false;
            this.TextBoxDataNascimento.Name = "TextBoxDataNascimento";
            stateProperties77.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.Color.Empty;
            stateProperties78.FillColor = System.Drawing.Color.White;
            stateProperties78.ForeColor = System.Drawing.Color.Empty;
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.Silver;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnIdleState = stateProperties80;
            this.TextBoxDataNascimento.PasswordChar = '\0';
            this.TextBoxDataNascimento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.PlaceholderText = "";
            this.TextBoxDataNascimento.ReadOnly = false;
            this.TextBoxDataNascimento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxDataNascimento.SelectedText = "";
            this.TextBoxDataNascimento.SelectionLength = 0;
            this.TextBoxDataNascimento.SelectionStart = 0;
            this.TextBoxDataNascimento.ShortcutsEnabled = true;
            this.TextBoxDataNascimento.Size = new System.Drawing.Size(189, 43);
            this.TextBoxDataNascimento.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxDataNascimento.TabIndex = 6;
            this.TextBoxDataNascimento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxDataNascimento.TextMarginBottom = 0;
            this.TextBoxDataNascimento.TextMarginLeft = 5;
            this.TextBoxDataNascimento.TextMarginTop = 0;
            this.TextBoxDataNascimento.TextPlaceholder = "";
            this.TextBoxDataNascimento.UseSystemPasswordChar = false;
            this.TextBoxDataNascimento.WordWrap = true;
            // 
            // lblNome
            // 
            this.lblNome.AutoSize = true;
            this.lblNome.Location = new System.Drawing.Point(73, 33);
            this.lblNome.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblNome.Name = "lblNome";
            this.lblNome.Size = new System.Drawing.Size(45, 17);
            this.lblNome.TabIndex = 5;
            this.lblNome.Text = "Nome";
            // 
            // frmCadastro_funcionario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ClientSize = new System.Drawing.Size(1081, 772);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "frmCadastro_funcionario";
            this.Text = "Cadastro De Cliente";
            this.Load += new System.EventHandler(this.Form_Cadastro_Cliente_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuCustomLabel lblSexo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxSexo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxNome;
        private Bunifu.Framework.UI.BunifuCustomLabel lblDataNascimento;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxEmail;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEmail;
        private System.Windows.Forms.RichTextBox TextBoxEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCelular;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCelular;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCPF;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCpf;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxRG;
        private Bunifu.Framework.UI.BunifuCustomLabel lblRG;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxTelefone;
        private Bunifu.Framework.UI.BunifuCustomLabel lblTelefone;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxDataNascimento;
        private Bunifu.Framework.UI.BunifuCustomLabel lblNome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Sair_ENTREGAS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_Salvar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCNH;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCnh;
    }
}