namespace PIM.View
{
    partial class frmCadastro_funcionario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCadastro_funcionario));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.lblSexo = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.lblDataNascimento = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.btnExcluir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPesquisar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TextBoxID = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblID = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxCNH = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCnh = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btnSalvar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblEndereco = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblEmail = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxEndereco = new System.Windows.Forms.RichTextBox();
            this.TextBoxCelular = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCelular = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxCPF = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblCpf = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxRG = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblRG = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxTelefone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblTelefone = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxDataNascimento = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblNome = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.TextBoxSexo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.TextBoxNome = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnSair = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblSexo
            // 
            this.lblSexo.AutoSize = true;
            this.lblSexo.Location = new System.Drawing.Point(427, 94);
            this.lblSexo.Name = "lblSexo";
            this.lblSexo.Size = new System.Drawing.Size(31, 13);
            this.lblSexo.TabIndex = 0;
            this.lblSexo.Text = "Sexo";
            // 
            // lblDataNascimento
            // 
            this.lblDataNascimento.AutoSize = true;
            this.lblDataNascimento.Location = new System.Drawing.Point(18, 149);
            this.lblDataNascimento.Name = "lblDataNascimento";
            this.lblDataNascimento.Size = new System.Drawing.Size(61, 13);
            this.lblDataNascimento.TabIndex = 3;
            this.lblDataNascimento.Text = "Data Nasc.";
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuShadowPanel1.Controls.Add(this.btnExcluir);
            this.bunifuShadowPanel1.Controls.Add(this.btnPesquisar);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxID);
            this.bunifuShadowPanel1.Controls.Add(this.lblID);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCNH);
            this.bunifuShadowPanel1.Controls.Add(this.lblCnh);
            this.bunifuShadowPanel1.Controls.Add(this.btnSalvar);
            this.bunifuShadowPanel1.Controls.Add(this.lblEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEmail);
            this.bunifuShadowPanel1.Controls.Add(this.lblEmail);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxEndereco);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCelular);
            this.bunifuShadowPanel1.Controls.Add(this.lblCelular);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxCPF);
            this.bunifuShadowPanel1.Controls.Add(this.lblCpf);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxRG);
            this.bunifuShadowPanel1.Controls.Add(this.lblRG);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.lblTelefone);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxDataNascimento);
            this.bunifuShadowPanel1.Controls.Add(this.lblNome);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxSexo);
            this.bunifuShadowPanel1.Controls.Add(this.lblSexo);
            this.bunifuShadowPanel1.Controls.Add(this.TextBoxNome);
            this.bunifuShadowPanel1.Controls.Add(this.lblDataNascimento);
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(12, 58);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.Empty;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(787, 613);
            this.bunifuShadowPanel1.TabIndex = 8;
            // 
            // btnExcluir
            // 
            this.btnExcluir.AllowToggling = false;
            this.btnExcluir.AnimationSpeed = 200;
            this.btnExcluir.AutoGenerateColors = false;
            this.btnExcluir.BackColor = System.Drawing.Color.Transparent;
            this.btnExcluir.BackColor1 = System.Drawing.Color.Red;
            this.btnExcluir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExcluir.BackgroundImage")));
            this.btnExcluir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExcluir.ButtonText = "Excluir";
            this.btnExcluir.ButtonTextMarginLeft = 0;
            this.btnExcluir.ColorContrastOnClick = 45;
            this.btnExcluir.ColorContrastOnHover = 45;
            this.btnExcluir.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnExcluir.CustomizableEdges = borderEdges1;
            this.btnExcluir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExcluir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExcluir.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExcluir.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExcluir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExcluir.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnExcluir.ForeColor = System.Drawing.Color.White;
            this.btnExcluir.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnExcluir.IconMarginLeft = 11;
            this.btnExcluir.IconPadding = 10;
            this.btnExcluir.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnExcluir.IdleBorderColor = System.Drawing.Color.Red;
            this.btnExcluir.IdleBorderRadius = 3;
            this.btnExcluir.IdleBorderThickness = 1;
            this.btnExcluir.IdleFillColor = System.Drawing.Color.Red;
            this.btnExcluir.IdleIconLeftImage = null;
            this.btnExcluir.IdleIconRightImage = null;
            this.btnExcluir.IndicateFocus = false;
            this.btnExcluir.Location = new System.Drawing.Point(85, 558);
            this.btnExcluir.Name = "btnExcluir";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties1.BorderRadius = 3;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnExcluir.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties2.BorderRadius = 3;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnExcluir.OnPressedState = stateProperties2;
            this.btnExcluir.Size = new System.Drawing.Size(57, 29);
            this.btnExcluir.TabIndex = 83;
            this.btnExcluir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExcluir.TextMarginLeft = 0;
            this.btnExcluir.UseDefaultRadiusAndThickness = true;
            // 
            // btnPesquisar
            // 
            this.btnPesquisar.AllowToggling = false;
            this.btnPesquisar.AnimationSpeed = 200;
            this.btnPesquisar.AutoGenerateColors = false;
            this.btnPesquisar.BackColor = System.Drawing.Color.Transparent;
            this.btnPesquisar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnPesquisar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPesquisar.BackgroundImage")));
            this.btnPesquisar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPesquisar.ButtonText = "Pesquisar";
            this.btnPesquisar.ButtonTextMarginLeft = 0;
            this.btnPesquisar.ColorContrastOnClick = 45;
            this.btnPesquisar.ColorContrastOnHover = 45;
            this.btnPesquisar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnPesquisar.CustomizableEdges = borderEdges2;
            this.btnPesquisar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPesquisar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPesquisar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPesquisar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPesquisar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPesquisar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnPesquisar.ForeColor = System.Drawing.Color.White;
            this.btnPesquisar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnPesquisar.IconMarginLeft = 11;
            this.btnPesquisar.IconPadding = 10;
            this.btnPesquisar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnPesquisar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnPesquisar.IdleBorderRadius = 3;
            this.btnPesquisar.IdleBorderThickness = 1;
            this.btnPesquisar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnPesquisar.IdleIconLeftImage = null;
            this.btnPesquisar.IdleIconRightImage = null;
            this.btnPesquisar.IndicateFocus = false;
            this.btnPesquisar.Location = new System.Drawing.Point(541, 558);
            this.btnPesquisar.Name = "btnPesquisar";
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.BorderRadius = 3;
            stateProperties3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties3.BorderThickness = 1;
            stateProperties3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.ForeColor = System.Drawing.Color.White;
            stateProperties3.IconLeftImage = null;
            stateProperties3.IconRightImage = null;
            this.btnPesquisar.onHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties4.BorderRadius = 3;
            stateProperties4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties4.BorderThickness = 1;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.IconLeftImage = null;
            stateProperties4.IconRightImage = null;
            this.btnPesquisar.OnPressedState = stateProperties4;
            this.btnPesquisar.Size = new System.Drawing.Size(95, 29);
            this.btnPesquisar.TabIndex = 82;
            this.btnPesquisar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPesquisar.TextMarginLeft = 0;
            this.btnPesquisar.UseDefaultRadiusAndThickness = true;
            // 
            // TextBoxID
            // 
            this.TextBoxID.AcceptsReturn = false;
            this.TextBoxID.AcceptsTab = false;
            this.TextBoxID.AnimationSpeed = 200;
            this.TextBoxID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxID.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxID.BackgroundImage")));
            this.TextBoxID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxID.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxID.BorderRadius = 1;
            this.TextBoxID.BorderThickness = 1;
            this.TextBoxID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxID.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxID.DefaultText = "";
            this.TextBoxID.FillColor = System.Drawing.Color.White;
            this.TextBoxID.HideSelection = true;
            this.TextBoxID.IconLeft = null;
            this.TextBoxID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxID.IconPadding = 10;
            this.TextBoxID.IconRight = null;
            this.TextBoxID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxID.Lines = new string[0];
            this.TextBoxID.Location = new System.Drawing.Point(85, 30);
            this.TextBoxID.MaxLength = 32767;
            this.TextBoxID.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxID.Modified = false;
            this.TextBoxID.Multiline = false;
            this.TextBoxID.Name = "TextBoxID";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxID.OnIdleState = stateProperties8;
            this.TextBoxID.PasswordChar = '\0';
            this.TextBoxID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxID.PlaceholderText = "";
            this.TextBoxID.ReadOnly = true;
            this.TextBoxID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxID.SelectedText = "";
            this.TextBoxID.SelectionLength = 0;
            this.TextBoxID.SelectionStart = 0;
            this.TextBoxID.ShortcutsEnabled = true;
            this.TextBoxID.Size = new System.Drawing.Size(100, 35);
            this.TextBoxID.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxID.TabIndex = 78;
            this.TextBoxID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxID.TextMarginBottom = 0;
            this.TextBoxID.TextMarginLeft = 5;
            this.TextBoxID.TextMarginTop = 0;
            this.TextBoxID.TextPlaceholder = "";
            this.TextBoxID.UseSystemPasswordChar = false;
            this.TextBoxID.WordWrap = true;
            // 
            // lblID
            // 
            this.lblID.AutoSize = true;
            this.lblID.Location = new System.Drawing.Point(56, 42);
            this.lblID.Name = "lblID";
            this.lblID.Size = new System.Drawing.Size(18, 13);
            this.lblID.TabIndex = 77;
            this.lblID.Text = "ID";
            // 
            // TextBoxCNH
            // 
            this.TextBoxCNH.AcceptsReturn = false;
            this.TextBoxCNH.AcceptsTab = false;
            this.TextBoxCNH.AnimationSpeed = 200;
            this.TextBoxCNH.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCNH.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCNH.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCNH.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCNH.BackgroundImage")));
            this.TextBoxCNH.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCNH.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCNH.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCNH.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCNH.BorderRadius = 1;
            this.TextBoxCNH.BorderThickness = 1;
            this.TextBoxCNH.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCNH.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCNH.DefaultText = "";
            this.TextBoxCNH.FillColor = System.Drawing.Color.White;
            this.TextBoxCNH.HideSelection = true;
            this.TextBoxCNH.IconLeft = null;
            this.TextBoxCNH.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.IconPadding = 10;
            this.TextBoxCNH.IconRight = null;
            this.TextBoxCNH.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCNH.Lines = new string[0];
            this.TextBoxCNH.Location = new System.Drawing.Point(464, 198);
            this.TextBoxCNH.MaxLength = 32767;
            this.TextBoxCNH.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxCNH.Modified = false;
            this.TextBoxCNH.Multiline = false;
            this.TextBoxCNH.Name = "TextBoxCNH";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCNH.OnIdleState = stateProperties12;
            this.TextBoxCNH.PasswordChar = '\0';
            this.TextBoxCNH.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCNH.PlaceholderText = "";
            this.TextBoxCNH.ReadOnly = false;
            this.TextBoxCNH.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCNH.SelectedText = "";
            this.TextBoxCNH.SelectionLength = 0;
            this.TextBoxCNH.SelectionStart = 0;
            this.TextBoxCNH.ShortcutsEnabled = true;
            this.TextBoxCNH.Size = new System.Drawing.Size(200, 35);
            this.TextBoxCNH.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCNH.TabIndex = 33;
            this.TextBoxCNH.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCNH.TextMarginBottom = 0;
            this.TextBoxCNH.TextMarginLeft = 5;
            this.TextBoxCNH.TextMarginTop = 0;
            this.TextBoxCNH.TextPlaceholder = "";
            this.TextBoxCNH.UseSystemPasswordChar = false;
            this.TextBoxCNH.WordWrap = true;
            // 
            // lblCnh
            // 
            this.lblCnh.AutoSize = true;
            this.lblCnh.Location = new System.Drawing.Point(427, 208);
            this.lblCnh.Name = "lblCnh";
            this.lblCnh.Size = new System.Drawing.Size(30, 13);
            this.lblCnh.TabIndex = 32;
            this.lblCnh.Text = "CNH";
            // 
            // btnSalvar
            // 
            this.btnSalvar.AllowToggling = false;
            this.btnSalvar.AnimationSpeed = 200;
            this.btnSalvar.AutoGenerateColors = false;
            this.btnSalvar.BackColor = System.Drawing.Color.Transparent;
            this.btnSalvar.BackColor1 = System.Drawing.Color.LimeGreen;
            this.btnSalvar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSalvar.BackgroundImage")));
            this.btnSalvar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalvar.ButtonText = "Salvar";
            this.btnSalvar.ButtonTextMarginLeft = 0;
            this.btnSalvar.ColorContrastOnClick = 45;
            this.btnSalvar.ColorContrastOnHover = 45;
            this.btnSalvar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSalvar.CustomizableEdges = borderEdges3;
            this.btnSalvar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSalvar.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSalvar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSalvar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSalvar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSalvar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSalvar.ForeColor = System.Drawing.Color.White;
            this.btnSalvar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSalvar.IconMarginLeft = 11;
            this.btnSalvar.IconPadding = 10;
            this.btnSalvar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSalvar.IdleBorderColor = System.Drawing.Color.LimeGreen;
            this.btnSalvar.IdleBorderRadius = 3;
            this.btnSalvar.IdleBorderThickness = 1;
            this.btnSalvar.IdleFillColor = System.Drawing.Color.LimeGreen;
            this.btnSalvar.IdleIconLeftImage = null;
            this.btnSalvar.IdleIconRightImage = null;
            this.btnSalvar.IndicateFocus = false;
            this.btnSalvar.Location = new System.Drawing.Point(333, 558);
            this.btnSalvar.Name = "btnSalvar";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.BorderRadius = 3;
            stateProperties13.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties13.BorderThickness = 1;
            stateProperties13.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.ForeColor = System.Drawing.Color.White;
            stateProperties13.IconLeftImage = null;
            stateProperties13.IconRightImage = null;
            this.btnSalvar.onHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties14.BorderRadius = 3;
            stateProperties14.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties14.BorderThickness = 1;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties14.ForeColor = System.Drawing.Color.White;
            stateProperties14.IconLeftImage = null;
            stateProperties14.IconRightImage = null;
            this.btnSalvar.OnPressedState = stateProperties14;
            this.btnSalvar.Size = new System.Drawing.Size(59, 29);
            this.btnSalvar.TabIndex = 31;
            this.btnSalvar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSalvar.TextMarginLeft = 0;
            this.btnSalvar.UseDefaultRadiusAndThickness = true;
            // 
            // lblEndereco
            // 
            this.lblEndereco.AutoSize = true;
            this.lblEndereco.Location = new System.Drawing.Point(26, 373);
            this.lblEndereco.Name = "lblEndereco";
            this.lblEndereco.Size = new System.Drawing.Size(53, 13);
            this.lblEndereco.TabIndex = 20;
            this.lblEndereco.Text = "Endereço";
            // 
            // TextBoxEmail
            // 
            this.TextBoxEmail.AcceptsReturn = false;
            this.TextBoxEmail.AcceptsTab = false;
            this.TextBoxEmail.AnimationSpeed = 200;
            this.TextBoxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxEmail.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxEmail.BackgroundImage")));
            this.TextBoxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxEmail.BorderRadius = 1;
            this.TextBoxEmail.BorderThickness = 1;
            this.TextBoxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxEmail.DefaultText = "";
            this.TextBoxEmail.FillColor = System.Drawing.Color.White;
            this.TextBoxEmail.HideSelection = true;
            this.TextBoxEmail.IconLeft = null;
            this.TextBoxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.IconPadding = 10;
            this.TextBoxEmail.IconRight = null;
            this.TextBoxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxEmail.Lines = new string[0];
            this.TextBoxEmail.Location = new System.Drawing.Point(85, 483);
            this.TextBoxEmail.MaxLength = 32767;
            this.TextBoxEmail.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxEmail.Modified = false;
            this.TextBoxEmail.Multiline = false;
            this.TextBoxEmail.Name = "TextBoxEmail";
            stateProperties15.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnActiveState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Empty;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.OnDisabledState = stateProperties16;
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnHoverState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Silver;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxEmail.OnIdleState = stateProperties18;
            this.TextBoxEmail.PasswordChar = '\0';
            this.TextBoxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxEmail.PlaceholderText = "";
            this.TextBoxEmail.ReadOnly = false;
            this.TextBoxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxEmail.SelectedText = "";
            this.TextBoxEmail.SelectionLength = 0;
            this.TextBoxEmail.SelectionStart = 0;
            this.TextBoxEmail.ShortcutsEnabled = true;
            this.TextBoxEmail.Size = new System.Drawing.Size(387, 35);
            this.TextBoxEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxEmail.TabIndex = 19;
            this.TextBoxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxEmail.TextMarginBottom = 0;
            this.TextBoxEmail.TextMarginLeft = 5;
            this.TextBoxEmail.TextMarginTop = 0;
            this.TextBoxEmail.TextPlaceholder = "";
            this.TextBoxEmail.UseSystemPasswordChar = false;
            this.TextBoxEmail.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Location = new System.Drawing.Point(44, 492);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(35, 13);
            this.lblEmail.TabIndex = 18;
            this.lblEmail.Text = "E-mail";
            // 
            // TextBoxEndereco
            // 
            this.TextBoxEndereco.Location = new System.Drawing.Point(85, 370);
            this.TextBoxEndereco.Name = "TextBoxEndereco";
            this.TextBoxEndereco.Size = new System.Drawing.Size(388, 87);
            this.TextBoxEndereco.TabIndex = 17;
            this.TextBoxEndereco.Text = "";
            // 
            // TextBoxCelular
            // 
            this.TextBoxCelular.AcceptsReturn = false;
            this.TextBoxCelular.AcceptsTab = false;
            this.TextBoxCelular.AnimationSpeed = 200;
            this.TextBoxCelular.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCelular.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCelular.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCelular.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCelular.BackgroundImage")));
            this.TextBoxCelular.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCelular.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCelular.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCelular.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCelular.BorderRadius = 1;
            this.TextBoxCelular.BorderThickness = 1;
            this.TextBoxCelular.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCelular.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCelular.DefaultText = "";
            this.TextBoxCelular.FillColor = System.Drawing.Color.White;
            this.TextBoxCelular.HideSelection = true;
            this.TextBoxCelular.IconLeft = null;
            this.TextBoxCelular.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.IconPadding = 10;
            this.TextBoxCelular.IconRight = null;
            this.TextBoxCelular.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCelular.Lines = new string[0];
            this.TextBoxCelular.Location = new System.Drawing.Point(464, 139);
            this.TextBoxCelular.MaxLength = 32767;
            this.TextBoxCelular.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxCelular.Modified = false;
            this.TextBoxCelular.Multiline = false;
            this.TextBoxCelular.Name = "TextBoxCelular";
            stateProperties19.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnActiveState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Empty;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.OnDisabledState = stateProperties20;
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Silver;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCelular.OnIdleState = stateProperties22;
            this.TextBoxCelular.PasswordChar = '\0';
            this.TextBoxCelular.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCelular.PlaceholderText = "";
            this.TextBoxCelular.ReadOnly = false;
            this.TextBoxCelular.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCelular.SelectedText = "";
            this.TextBoxCelular.SelectionLength = 0;
            this.TextBoxCelular.SelectionStart = 0;
            this.TextBoxCelular.ShortcutsEnabled = true;
            this.TextBoxCelular.Size = new System.Drawing.Size(200, 35);
            this.TextBoxCelular.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCelular.TabIndex = 14;
            this.TextBoxCelular.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCelular.TextMarginBottom = 0;
            this.TextBoxCelular.TextMarginLeft = 5;
            this.TextBoxCelular.TextMarginTop = 0;
            this.TextBoxCelular.TextPlaceholder = "";
            this.TextBoxCelular.UseSystemPasswordChar = false;
            this.TextBoxCelular.WordWrap = true;
            // 
            // lblCelular
            // 
            this.lblCelular.AutoSize = true;
            this.lblCelular.Location = new System.Drawing.Point(419, 149);
            this.lblCelular.Name = "lblCelular";
            this.lblCelular.Size = new System.Drawing.Size(39, 13);
            this.lblCelular.TabIndex = 13;
            this.lblCelular.Text = "Celular";
            // 
            // TextBoxCPF
            // 
            this.TextBoxCPF.AcceptsReturn = false;
            this.TextBoxCPF.AcceptsTab = false;
            this.TextBoxCPF.AnimationSpeed = 200;
            this.TextBoxCPF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxCPF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxCPF.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxCPF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxCPF.BackgroundImage")));
            this.TextBoxCPF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxCPF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxCPF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxCPF.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxCPF.BorderRadius = 1;
            this.TextBoxCPF.BorderThickness = 1;
            this.TextBoxCPF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxCPF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxCPF.DefaultText = "";
            this.TextBoxCPF.FillColor = System.Drawing.Color.White;
            this.TextBoxCPF.HideSelection = true;
            this.TextBoxCPF.IconLeft = null;
            this.TextBoxCPF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.IconPadding = 10;
            this.TextBoxCPF.IconRight = null;
            this.TextBoxCPF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxCPF.Lines = new string[0];
            this.TextBoxCPF.Location = new System.Drawing.Point(85, 305);
            this.TextBoxCPF.MaxLength = 32767;
            this.TextBoxCPF.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxCPF.Modified = false;
            this.TextBoxCPF.Multiline = false;
            this.TextBoxCPF.Name = "TextBoxCPF";
            stateProperties23.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnActiveState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Empty;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.OnDisabledState = stateProperties24;
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Silver;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxCPF.OnIdleState = stateProperties26;
            this.TextBoxCPF.PasswordChar = '\0';
            this.TextBoxCPF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxCPF.PlaceholderText = "";
            this.TextBoxCPF.ReadOnly = false;
            this.TextBoxCPF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxCPF.SelectedText = "";
            this.TextBoxCPF.SelectionLength = 0;
            this.TextBoxCPF.SelectionStart = 0;
            this.TextBoxCPF.ShortcutsEnabled = true;
            this.TextBoxCPF.Size = new System.Drawing.Size(200, 35);
            this.TextBoxCPF.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxCPF.TabIndex = 12;
            this.TextBoxCPF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxCPF.TextMarginBottom = 0;
            this.TextBoxCPF.TextMarginLeft = 5;
            this.TextBoxCPF.TextMarginTop = 0;
            this.TextBoxCPF.TextPlaceholder = "";
            this.TextBoxCPF.UseSystemPasswordChar = false;
            this.TextBoxCPF.WordWrap = true;
            // 
            // lblCpf
            // 
            this.lblCpf.AutoSize = true;
            this.lblCpf.Location = new System.Drawing.Point(52, 317);
            this.lblCpf.Name = "lblCpf";
            this.lblCpf.Size = new System.Drawing.Size(27, 13);
            this.lblCpf.TabIndex = 11;
            this.lblCpf.Text = "CPF";
            // 
            // TextBoxRG
            // 
            this.TextBoxRG.AcceptsReturn = false;
            this.TextBoxRG.AcceptsTab = false;
            this.TextBoxRG.AnimationSpeed = 200;
            this.TextBoxRG.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxRG.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxRG.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxRG.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxRG.BackgroundImage")));
            this.TextBoxRG.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxRG.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxRG.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxRG.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxRG.BorderRadius = 1;
            this.TextBoxRG.BorderThickness = 1;
            this.TextBoxRG.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxRG.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxRG.DefaultText = "";
            this.TextBoxRG.FillColor = System.Drawing.Color.White;
            this.TextBoxRG.HideSelection = true;
            this.TextBoxRG.IconLeft = null;
            this.TextBoxRG.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.IconPadding = 10;
            this.TextBoxRG.IconRight = null;
            this.TextBoxRG.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxRG.Lines = new string[0];
            this.TextBoxRG.Location = new System.Drawing.Point(85, 243);
            this.TextBoxRG.MaxLength = 32767;
            this.TextBoxRG.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxRG.Modified = false;
            this.TextBoxRG.Multiline = false;
            this.TextBoxRG.Name = "TextBoxRG";
            stateProperties27.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnActiveState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Empty;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.OnDisabledState = stateProperties28;
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Silver;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxRG.OnIdleState = stateProperties30;
            this.TextBoxRG.PasswordChar = '\0';
            this.TextBoxRG.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxRG.PlaceholderText = "";
            this.TextBoxRG.ReadOnly = false;
            this.TextBoxRG.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxRG.SelectedText = "";
            this.TextBoxRG.SelectionLength = 0;
            this.TextBoxRG.SelectionStart = 0;
            this.TextBoxRG.ShortcutsEnabled = true;
            this.TextBoxRG.Size = new System.Drawing.Size(200, 35);
            this.TextBoxRG.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxRG.TabIndex = 10;
            this.TextBoxRG.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxRG.TextMarginBottom = 0;
            this.TextBoxRG.TextMarginLeft = 5;
            this.TextBoxRG.TextMarginTop = 0;
            this.TextBoxRG.TextPlaceholder = "";
            this.TextBoxRG.UseSystemPasswordChar = false;
            this.TextBoxRG.WordWrap = true;
            // 
            // lblRG
            // 
            this.lblRG.AutoSize = true;
            this.lblRG.Location = new System.Drawing.Point(56, 255);
            this.lblRG.Name = "lblRG";
            this.lblRG.Size = new System.Drawing.Size(23, 13);
            this.lblRG.TabIndex = 9;
            this.lblRG.Text = "RG";
            // 
            // TextBoxTelefone
            // 
            this.TextBoxTelefone.AcceptsReturn = false;
            this.TextBoxTelefone.AcceptsTab = false;
            this.TextBoxTelefone.AnimationSpeed = 200;
            this.TextBoxTelefone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTelefone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTelefone.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxTelefone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTelefone.BackgroundImage")));
            this.TextBoxTelefone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxTelefone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxTelefone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxTelefone.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTelefone.BorderRadius = 1;
            this.TextBoxTelefone.BorderThickness = 1;
            this.TextBoxTelefone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTelefone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxTelefone.DefaultText = "";
            this.TextBoxTelefone.FillColor = System.Drawing.Color.White;
            this.TextBoxTelefone.HideSelection = true;
            this.TextBoxTelefone.IconLeft = null;
            this.TextBoxTelefone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.IconPadding = 10;
            this.TextBoxTelefone.IconRight = null;
            this.TextBoxTelefone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTelefone.Lines = new string[0];
            this.TextBoxTelefone.Location = new System.Drawing.Point(85, 187);
            this.TextBoxTelefone.MaxLength = 32767;
            this.TextBoxTelefone.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxTelefone.Modified = false;
            this.TextBoxTelefone.Multiline = false;
            this.TextBoxTelefone.Name = "TextBoxTelefone";
            stateProperties31.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnActiveState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Empty;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.OnDisabledState = stateProperties32;
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnHoverState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Silver;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTelefone.OnIdleState = stateProperties34;
            this.TextBoxTelefone.PasswordChar = '\0';
            this.TextBoxTelefone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTelefone.PlaceholderText = "";
            this.TextBoxTelefone.ReadOnly = false;
            this.TextBoxTelefone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTelefone.SelectedText = "";
            this.TextBoxTelefone.SelectionLength = 0;
            this.TextBoxTelefone.SelectionStart = 0;
            this.TextBoxTelefone.ShortcutsEnabled = true;
            this.TextBoxTelefone.Size = new System.Drawing.Size(200, 35);
            this.TextBoxTelefone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxTelefone.TabIndex = 8;
            this.TextBoxTelefone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxTelefone.TextMarginBottom = 0;
            this.TextBoxTelefone.TextMarginLeft = 5;
            this.TextBoxTelefone.TextMarginTop = 0;
            this.TextBoxTelefone.TextPlaceholder = "";
            this.TextBoxTelefone.UseSystemPasswordChar = false;
            this.TextBoxTelefone.WordWrap = true;
            // 
            // lblTelefone
            // 
            this.lblTelefone.AutoSize = true;
            this.lblTelefone.Location = new System.Drawing.Point(30, 198);
            this.lblTelefone.Name = "lblTelefone";
            this.lblTelefone.Size = new System.Drawing.Size(49, 13);
            this.lblTelefone.TabIndex = 7;
            this.lblTelefone.Text = "Telefone";
            // 
            // TextBoxDataNascimento
            // 
            this.TextBoxDataNascimento.AcceptsReturn = false;
            this.TextBoxDataNascimento.AcceptsTab = false;
            this.TextBoxDataNascimento.AnimationSpeed = 200;
            this.TextBoxDataNascimento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxDataNascimento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxDataNascimento.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxDataNascimento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxDataNascimento.BackgroundImage")));
            this.TextBoxDataNascimento.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxDataNascimento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxDataNascimento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxDataNascimento.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.BorderRadius = 1;
            this.TextBoxDataNascimento.BorderThickness = 1;
            this.TextBoxDataNascimento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxDataNascimento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxDataNascimento.DefaultText = "";
            this.TextBoxDataNascimento.FillColor = System.Drawing.Color.White;
            this.TextBoxDataNascimento.HideSelection = true;
            this.TextBoxDataNascimento.IconLeft = null;
            this.TextBoxDataNascimento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.IconPadding = 10;
            this.TextBoxDataNascimento.IconRight = null;
            this.TextBoxDataNascimento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxDataNascimento.Lines = new string[0];
            this.TextBoxDataNascimento.Location = new System.Drawing.Point(85, 139);
            this.TextBoxDataNascimento.MaxLength = 32767;
            this.TextBoxDataNascimento.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxDataNascimento.Modified = false;
            this.TextBoxDataNascimento.Multiline = false;
            this.TextBoxDataNascimento.Name = "TextBoxDataNascimento";
            stateProperties35.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnActiveState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Empty;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.OnDisabledState = stateProperties36;
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnHoverState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Silver;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxDataNascimento.OnIdleState = stateProperties38;
            this.TextBoxDataNascimento.PasswordChar = '\0';
            this.TextBoxDataNascimento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxDataNascimento.PlaceholderText = "";
            this.TextBoxDataNascimento.ReadOnly = false;
            this.TextBoxDataNascimento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxDataNascimento.SelectedText = "";
            this.TextBoxDataNascimento.SelectionLength = 0;
            this.TextBoxDataNascimento.SelectionStart = 0;
            this.TextBoxDataNascimento.ShortcutsEnabled = true;
            this.TextBoxDataNascimento.Size = new System.Drawing.Size(109, 35);
            this.TextBoxDataNascimento.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxDataNascimento.TabIndex = 6;
            this.TextBoxDataNascimento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxDataNascimento.TextMarginBottom = 0;
            this.TextBoxDataNascimento.TextMarginLeft = 5;
            this.TextBoxDataNascimento.TextMarginTop = 0;
            this.TextBoxDataNascimento.TextPlaceholder = "";
            this.TextBoxDataNascimento.UseSystemPasswordChar = false;
            this.TextBoxDataNascimento.WordWrap = true;
            // 
            // lblNome
            // 
            this.lblNome.AutoSize = true;
            this.lblNome.Location = new System.Drawing.Point(44, 94);
            this.lblNome.Name = "lblNome";
            this.lblNome.Size = new System.Drawing.Size(35, 13);
            this.lblNome.TabIndex = 5;
            this.lblNome.Text = "Nome";
            // 
            // TextBoxSexo
            // 
            this.TextBoxSexo.AcceptsReturn = false;
            this.TextBoxSexo.AcceptsTab = false;
            this.TextBoxSexo.AnimationSpeed = 200;
            this.TextBoxSexo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxSexo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxSexo.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxSexo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxSexo.BackgroundImage")));
            this.TextBoxSexo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxSexo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxSexo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxSexo.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxSexo.BorderRadius = 1;
            this.TextBoxSexo.BorderThickness = 1;
            this.TextBoxSexo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxSexo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxSexo.DefaultText = "";
            this.TextBoxSexo.FillColor = System.Drawing.Color.White;
            this.TextBoxSexo.HideSelection = true;
            this.TextBoxSexo.IconLeft = null;
            this.TextBoxSexo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.IconPadding = 10;
            this.TextBoxSexo.IconRight = null;
            this.TextBoxSexo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxSexo.Lines = new string[0];
            this.TextBoxSexo.Location = new System.Drawing.Point(464, 84);
            this.TextBoxSexo.MaxLength = 32767;
            this.TextBoxSexo.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxSexo.Modified = false;
            this.TextBoxSexo.Multiline = false;
            this.TextBoxSexo.Name = "TextBoxSexo";
            stateProperties39.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnActiveState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Empty;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.OnDisabledState = stateProperties40;
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnHoverState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Silver;
            stateProperties42.FillColor = System.Drawing.Color.White;
            stateProperties42.ForeColor = System.Drawing.Color.Empty;
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxSexo.OnIdleState = stateProperties42;
            this.TextBoxSexo.PasswordChar = '\0';
            this.TextBoxSexo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxSexo.PlaceholderText = "";
            this.TextBoxSexo.ReadOnly = false;
            this.TextBoxSexo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxSexo.SelectedText = "";
            this.TextBoxSexo.SelectionLength = 0;
            this.TextBoxSexo.SelectionStart = 0;
            this.TextBoxSexo.ShortcutsEnabled = true;
            this.TextBoxSexo.Size = new System.Drawing.Size(105, 35);
            this.TextBoxSexo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxSexo.TabIndex = 2;
            this.TextBoxSexo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxSexo.TextMarginBottom = 0;
            this.TextBoxSexo.TextMarginLeft = 5;
            this.TextBoxSexo.TextMarginTop = 0;
            this.TextBoxSexo.TextPlaceholder = "";
            this.TextBoxSexo.UseSystemPasswordChar = false;
            this.TextBoxSexo.WordWrap = true;
            this.TextBoxSexo.TextChanged += new System.EventHandler(this.TextBoxSexo_TextChanged);
            // 
            // TextBoxNome
            // 
            this.TextBoxNome.AcceptsReturn = false;
            this.TextBoxNome.AcceptsTab = false;
            this.TextBoxNome.AnimationSpeed = 200;
            this.TextBoxNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxNome.BackColor = System.Drawing.Color.Transparent;
            this.TextBoxNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxNome.BackgroundImage")));
            this.TextBoxNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.TextBoxNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.TextBoxNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.TextBoxNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxNome.BorderRadius = 1;
            this.TextBoxNome.BorderThickness = 1;
            this.TextBoxNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.TextBoxNome.DefaultText = "";
            this.TextBoxNome.FillColor = System.Drawing.Color.White;
            this.TextBoxNome.HideSelection = true;
            this.TextBoxNome.IconLeft = null;
            this.TextBoxNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.IconPadding = 10;
            this.TextBoxNome.IconRight = null;
            this.TextBoxNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxNome.Lines = new string[0];
            this.TextBoxNome.Location = new System.Drawing.Point(85, 84);
            this.TextBoxNome.MaxLength = 32767;
            this.TextBoxNome.MinimumSize = new System.Drawing.Size(100, 35);
            this.TextBoxNome.Modified = false;
            this.TextBoxNome.Multiline = false;
            this.TextBoxNome.Name = "TextBoxNome";
            stateProperties43.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnActiveState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Empty;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.OnDisabledState = stateProperties44;
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnHoverState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Silver;
            stateProperties46.FillColor = System.Drawing.Color.White;
            stateProperties46.ForeColor = System.Drawing.Color.Empty;
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxNome.OnIdleState = stateProperties46;
            this.TextBoxNome.PasswordChar = '\0';
            this.TextBoxNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxNome.PlaceholderText = "";
            this.TextBoxNome.ReadOnly = false;
            this.TextBoxNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxNome.SelectedText = "";
            this.TextBoxNome.SelectionLength = 0;
            this.TextBoxNome.SelectionStart = 0;
            this.TextBoxNome.ShortcutsEnabled = true;
            this.TextBoxNome.Size = new System.Drawing.Size(233, 35);
            this.TextBoxNome.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.TextBoxNome.TabIndex = 4;
            this.TextBoxNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxNome.TextMarginBottom = 0;
            this.TextBoxNome.TextMarginLeft = 5;
            this.TextBoxNome.TextMarginTop = 0;
            this.TextBoxNome.TextPlaceholder = "";
            this.TextBoxNome.UseSystemPasswordChar = false;
            this.TextBoxNome.WordWrap = true;
            this.TextBoxNome.TextChanged += new System.EventHandler(this.TextBoxNome_TextChanged);
            // 
            // btnSair
            // 
            this.btnSair.AllowToggling = false;
            this.btnSair.AnimationSpeed = 200;
            this.btnSair.AutoGenerateColors = false;
            this.btnSair.BackColor = System.Drawing.Color.Transparent;
            this.btnSair.BackColor1 = System.Drawing.Color.Red;
            this.btnSair.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSair.BackgroundImage")));
            this.btnSair.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSair.ButtonText = "X";
            this.btnSair.ButtonTextMarginLeft = 0;
            this.btnSair.ColorContrastOnClick = 45;
            this.btnSair.ColorContrastOnHover = 45;
            this.btnSair.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSair.CustomizableEdges = borderEdges4;
            this.btnSair.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSair.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnSair.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSair.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSair.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSair.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSair.ForeColor = System.Drawing.Color.White;
            this.btnSair.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSair.IconMarginLeft = 11;
            this.btnSair.IconPadding = 10;
            this.btnSair.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSair.IdleBorderColor = System.Drawing.Color.Red;
            this.btnSair.IdleBorderRadius = 3;
            this.btnSair.IdleBorderThickness = 1;
            this.btnSair.IdleFillColor = System.Drawing.Color.Red;
            this.btnSair.IdleIconLeftImage = null;
            this.btnSair.IdleIconRightImage = null;
            this.btnSair.IndicateFocus = false;
            this.btnSair.Location = new System.Drawing.Point(761, 12);
            this.btnSair.Name = "btnSair";
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.BorderRadius = 3;
            stateProperties47.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties47.BorderThickness = 1;
            stateProperties47.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.ForeColor = System.Drawing.Color.White;
            stateProperties47.IconLeftImage = null;
            stateProperties47.IconRightImage = null;
            this.btnSair.onHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties48.BorderRadius = 3;
            stateProperties48.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties48.BorderThickness = 1;
            stateProperties48.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties48.ForeColor = System.Drawing.Color.White;
            stateProperties48.IconLeftImage = null;
            stateProperties48.IconRightImage = null;
            this.btnSair.OnPressedState = stateProperties48;
            this.btnSair.Size = new System.Drawing.Size(38, 29);
            this.btnSair.TabIndex = 30;
            this.btnSair.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSair.TextMarginLeft = 0;
            this.btnSair.UseDefaultRadiusAndThickness = true;
            this.btnSair.Click += new System.EventHandler(this.btn_Sair_ENTREGAS_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.BackColor = System.Drawing.Color.White;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 15F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 26);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(217, 27);
            this.bunifuLabel2.TabIndex = 33;
            this.bunifuLabel2.Text = "Cadastro de Funcionario";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // frmCadastro_funcionario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.ClientSize = new System.Drawing.Size(811, 684);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuShadowPanel1);
            this.Controls.Add(this.btnSair);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "frmCadastro_funcionario";
            this.Text = "Cadastro De Cliente";
            this.Load += new System.EventHandler(this.Form_Cadastro_Cliente_Load);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuCustomLabel lblSexo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxNome;
        private Bunifu.Framework.UI.BunifuCustomLabel lblDataNascimento;
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxEmail;
        private Bunifu.Framework.UI.BunifuCustomLabel lblEmail;
        private System.Windows.Forms.RichTextBox TextBoxEndereco;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCelular;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCelular;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCPF;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCpf;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxRG;
        private Bunifu.Framework.UI.BunifuCustomLabel lblRG;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxTelefone;
        private Bunifu.Framework.UI.BunifuCustomLabel lblTelefone;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxDataNascimento;
        private Bunifu.Framework.UI.BunifuCustomLabel lblNome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSair;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSalvar;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxCNH;
        private Bunifu.Framework.UI.BunifuCustomLabel lblCnh;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxSexo;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox TextBoxID;
        private Bunifu.Framework.UI.BunifuCustomLabel lblID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExcluir;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPesquisar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
    }
}